### ISSUE TITLE
Add chrome binary names in (arch) linux

### ISSUE THREAD

**Issue by chendaniely** [rstudio/pagedown#104]
In the `find_chrome` function the name of the chrome binaries are hardcoded as ` c("google-chrome", "chromium-browser", "chromium")` what would be the best way to add additional binary names to the character vector?

For example, on Arch linux my binary is named `google-chrome-stable` is it better to send a PR with that hardcoded binary? or have a function default parameter something like `function(linux_bin_names =  c("google-chrome", "chromium-browser", "chromium")`)` but have the user be able to add additional search names?

**Comment by yihui** [comment]
I guess you are actually using the `chrome_print()` function. If that is the case, you can `chrome_print(..., browser = 'google-chrome-stable')`.

I'm okay with adding `google-chrome-stable` to the candidate list (please feel free to submit a PR).

**Comment by chendaniely** [comment]
Yes, I am using `chrome_print()`, thanks for the `browser = 'google-chrome-stable'` solution.
