### ISSUE TITLE
chrome_print(output = "*.pdf") can't render `--` and `count: false`

### ISSUE THREAD

**Issue by abichat** [rstudio/pagedown#110]
I have an issue about how `xaringan` pauses are rendered by `chrome_print()` in `.pdf`.

Reprex:

```
---
title: "Reprex"
author: "AB"
date: "`r Sys.Date()`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

 ```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
 ``` # Remove the #


# Slide one

Hello 

--

First pause

--

Second pause


---
# Slide two

---
count: false
# Slide three


---
class: center, middle

# Thanks!
```

In `.html`, there is 7 slides. Three are numbered `2/4` (with `--`) and two `3/4` (with `count: false). 

However, when I used `pagedown::chrome_print(input = "reprex.Rmd", output = "reprex.pdf")` (or direclty from chrome), the `.pdf` has only 4 slides : only the last one is kept per page number. 

These slides have the class `has-continuation`, and it renders correctly when I remove it manually and print from chrome. 

Thanks :)

**Comment by cderv** [comment]
Hi,

Does it work as expected when opening your html xaringan présentation in chrome and printing to pdf from there ? 

I suspect it is not. 

I think this is not an issue with pagedown. It could be related to discussion in yihui/xaringan#192

Have you tried with last dev xaringan version including the fix for #192 ? 

I could come from remark.js directly. I need to test further and see how to adapt the solution if it does not work.

**Comment by RLesur** [comment]
Just an idea: if the rendering is ok after removing the `has-continuation` class, maybe we could remove this class with JS before generating the pdf with `chrome_print()`.
I'll give it a try.

**Comment by abichat** [comment]
It still don't work _as I expected_ with **xaringan** 0.10.1.

But as you pointed out with the discussion, my issue is actually a desired feature :
> When printing slides to PDF, only the last slide of a series of incremental slides will be printed. 

(from **xaringan** 0.9 [NEWS file](https://github.com/yihui/xaringan/blob/master/NEWS.md).)

**Comment by cderv** [comment]
@RLesur, removing this class was just a workaround as a result of an investigation of mine when it happened. 

I think it needs to be looked into thoroughly to understand what is the real issue here. 

I’ll try to find time for that.

**Comment by RLesur** [comment]
In order to include this solution in a CSS file, you need tweak the CSS declaration:

```css
@media print {
  .has-continuation {
    display: block !important;
  }
}
```

**Comment by privefl** [comment]
`xaringanBuilder::build_pdf(..., partial_slides = TRUE)` works well for me.
