### ISSUE TITLE
Error when rendering letter, thesis, and paged html templates

### ISSUE THREAD

**Issue by potterzot** [rstudio/pagedown#112]
When opening a default template for one of [HTML Letter, HTML Thesis Document, Paged HTML Document] I get the following error when attempting to knit. This does not occur with the resume or business card templates.

```r
Error running filter /home/potterzot/.R/3.6/pagedown/resources/lua/uri-to-fn.lua:
Error while running filter function: /home/potterzot/.R/3.6/pagedown/resources/lua/uri-to-fn.lua:30: attempt to index a nil value (field 'utils')
Error: pandoc document conversion failed with error 83
Execution halted
```

System details:
- Linux
- `R` version: 3.6.0 (2019-04-26)
- `rstudio` version: 1.2.1335
- `pagedown` version: 0.2.9, installed this morning with `devtools::install_github("rstudio/pagedown")`

**Comment by RLesur** [comment]
Thanks for the report. This is related to Pandoc. Could you add your Pandoc version, please?

**Comment by potterzot** [comment]
Ah thank you, my pandoc version was 2.0.1. Updated to 2.7.3 and issues are fixed. Sorry for the needless issue!

**Comment by RLesur** [comment]
No problem!
We could internally check the Pandoc version and throw a more explicit error.
