### ISSUE TITLE
Numbered example lists is not working

### ISSUE THREAD

**Issue by atusy** [rstudio/pagedown#122]
Pandoc supports numbered example lists, which sequentially count items throughout the document. https://pandoc.org/MANUAL.html#numbered-example-lists

This feature works in `rmarkdown::html_document`, but not in `pagedown::html_paged`

## htmll_document

![image](https://user-images.githubusercontent.com/30277794/61189668-81eee600-a6cb-11e9-96b4-645694aa730e.png)

## html_paged

![image](https://user-images.githubusercontent.com/30277794/61189661-73083380-a6cb-11e9-89c9-e95bd056eae8.png)

## Source

````
---
output: 
  html_document: default
  pagedown::html_paged: default
---


(@) is 1

and

(@) should be 2
````

**Comment by RLesur** [comment]
I had a quick look. It seems to be a bug in Paged.js.
I have opened an issue in the Paged.js project https://gitlab.pagedmedia.org/tools/pagedjs/issues/130

**Comment by RLesur** [comment]
FTR, this is now fixed in the development version of Paged.js (see https://gitlab.pagedmedia.org/tools/pagedjs/merge_requests/111).

**Comment by atusy** [comment]
How nice!
