### ISSUE TITLE
Support multiple RMD files

### ISSUE THREAD

**Issue by DavisBrian** [rstudio/pagedown#128]
As far as I can tell there isn't a way to split an html_paged document across multiple rmd files (ala bookdown), everything must be in one rmd file.  Is this correct?

**Comment by cderv** [comment]
I think you can use bookdown 📦 with a `pagedown::html_paged` format. 

In your `_output.yml` file in a bookdown project, try add 
```yaml
pagedown::html_paged: default
```
or with option. Then, build the book (using RStudio IDE button or `bookdown::render_book`. 
I think it should work as expected. At least in the test I did, it worked :)

**Comment by DavisBrian** [comment]
Thanks for the info.  I'll keep looking into it but now I get
Warning messages:
1: MathJax doesn't work with self_contained when not using the rmarkdown "default" template. 

The first couple chapters are fairly simple some tables (with kableextra) and plots.  Very little text even.

my _output.yml looks like
pagedown::html_paged: default
bookdown::gitbook:
  css: css/style.css
  table_css: false
  config:
    toc:
      collapse: subsection
      before: |
        <li><a href="./">RADARS® System Subscriber Report</a></li>
        <li><a href="./">1st Quarter 2019</a></li>
      scroll_highlight: yes
    sharing: no

**Comment by RLesur** [comment]
@DavisBrian With the development version of **pagedown**, you should be able to render your book without this warning.

**Comment by cderv** [comment]
Thanks @Rlesur !

**Comment by DavisBrian** [comment]
Thanks! @RLesur .  This will be  great help.

**Comment by alsmnn** [comment]
First of all sorry for hijacking this issue, but I think my question is relevant to the multi Rmd-file approach. I never used bookdown before, but I would like to be able to use:

* cover_letter.Rmd for the cover letter
* resume.Rmd for the resume

Is there an easy way to accomplish this in order to get one html file consisting of multiple pages? This would make the pdf creation for an application so much easier.

Cheers!

**Comment by cderv** [comment]
Bookdown is a tool to create book-like content and it allows to split in multiple Rmd source file to create one format. Cover letter and Resume are not the same document here. So you need to create two source document.

> This would make the pdf creation for an application so much easier.

What is the aim here ? 

You could have a Rmd document for cover letter and another one for resume. Then you could have a script that renders and prints them to pdf, then if desired merges the two pdf in one document (ie using `pdftools` 📦 ). Is this the type of output you seek ? 

For new question, even related to possibly related topic, please open new issues that you can linked to others. Also, consider community.rstudio.com for question

**Comment by alsmnn** [comment]
Thanks for the short info about bookdown. I will definitely have a look into that. 

> What is the aim here ?
The aim is to produce one single html file consisting of the cover letter and the resume in order to print it to a pdf with chrome. 
I think, I just need to get familiar with bookdown in order to accomplish this.
Thanks for your time!

**Comment by cderv** [comment]
> The aim is to produce one single html file consisting of the cover letter and the resume in order to print it to a pdf with chrome.


cover letter and resume in pagedown are two different layouts. The css and html code are not the same and I don't know how you would create one html with both inside. (🤔  i am even unsure it is possible or it would be require some _heavy_ customisation).

I understand that you want one pdf at the end. I would approach that with a maybe more pragmatic solutions: 

* by rendering two pdf : one from resume and one from cover letter,
* then merge them together into one pdf. 

Doing all that programmatically with a wrapper function I guess 
```r
print_cover_resume(cover_file, resume_file, pdf_output)
```

Would it work for you ?
I can provide a small example or hints on how to achieve that.
