### ISSUE TITLE
Improve MathJax support

### ISSUE THREAD

**Issue by RLesur** [rstudio/pagedown#130]
There are two bugs with MathJax:

1. Use of a local version of MathJax
`pagedown::html_paged(self_contained = FALSE, mathjax = "local")` does not use the local version of MathJax.

2. Self contained documents
    - with `self_contained = TRUE`, maths are not rendered with MathJax. For now, a simple workaround is to use `pandoc_args = "--mathjax"` (I saw that @brentthorne uses this trick).
    - **rmarkdown** throws the following warning 
    ```
    MathJax doesn't work with self_contained when not using the rmarkdown "default" template.
    ```
    see https://github.com/rstudio/pagedown/issues/128#issuecomment-518371613

**Comment by RLesur** [comment]
@brentthorne With the development version of **pagedown**, you no longer need to use `pandoc_args="mathjax"` (there is no problem if you use it).

**Comment by brentthorne** [comment]
Great thank you!
