### ISSUE TITLE
chrome_print() inside rocker container fails without `--no-sandbox`

### ISSUE THREAD

**Issue by rensa** [rstudio/pagedown#143]
I'm using `pagedown::chrome_print()` inside a Docker container, and I've found that if I call it naively, I get:

```r
chrome_print('/test.rmd', browser = 'chromium', verbose = 2)
# Using the browser "/usr/bin/chromium"
# Checking the remote connection in 20 attempts.
# Error in is_remote_protocol_ok(debug_port, verbose = verbose) :
#   Cannot connect to headless Chrome after 20 attempts
# Closing browser
# Cleaning browser working directory
```

Whereas if I add `extra_args = '--no-sandbox'`, PDFs render fine.

In my quick Googling and StackOverflowing, I see that running Chrome/Chromium without the sandbox is generally a Bad Idea (although I'm sceptical about just how bad an idea it is when Chromium is running inside a container for the sole purpose of rendering PDFs of my RMarkdown reports).

I'm wondering whether it's expected that `--no-sandbox` be used either inside a container or on Linux generally (I typically work on Windows, so I haven't run Chromium on Linux before). If not, maybe I need to work on my configuration a bit more, but I thought I'd ask first 😄

**Comment by rensa** [comment]
Oh, this might be because I'm shelling into my container as root and [you apparently can't run Chromium as root without `--no-sandbox`](https://github.com/karma-runner/karma-chrome-launcher/issues/158). I'll run a couple of tests as non-root 😅

**Comment by RLesur** [comment]
Inside a container, I always need the `--disable-gpu` flag. I know that it is possible to run as non-root but I have never tried, see for instance [justinribeiro/chrome-headless](https://hub.docker.com/r/justinribeiro/chrome-headless/).

**Comment by rensa** [comment]
That's good to know, @RLesur! I tried removing `--disable-gpu` and was successful, but it was a reeeeaaally simple test (just a heading and text, no images or code).

**Comment by muschellij2** [comment]
FYI, I've had failures with Chromium, but not with Chrome itself - figured that out via https://datawookie.dev/blog/2021/05/using-pagedown-in-docker/, but I'd recommend using  `wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb` as opposed to the bitly link there.
