### ISSUE TITLE
paged thesis tempalte not rendering

### ISSUE THREAD

**Issue by mr-illington** [rstudio/pagedown#144]
Hello and thanks for this wonderful package. I have already implemented it to success on a CV, but am having trouble with the paged thesis template. 

Specifically, the a stock pagedown thesis template knitted to html flashes for only a second and then does not load in both Chrome and Firefox browsers. By contrast, the html does load in IE and the default RStudio viewer.

Both normal .Rmd files and the pagedown thesis html output for my CV application however DO load in the respective Chrome and Firefox browsers on the same computer. Therefore the issue would seem to point to the paged thesis template contribution.  

I've looked for elements being blocked etc. from the browser side but have found nothing obvious there. 

Has anyone had similar issues with paged thesis?

**Comment by RLesur** [comment]
Do you get the same issue with the following url: https://pagedown.rbind.io/thesis-paged?

**Comment by mr-illington** [comment]
No - this loads. 

Does this suggest it is something to do with how my file is being knitted locally?

**Comment by RLesur** [comment]
In order to try to identify the problem, I have one more question: do you confirm that you use a local web server as explained in the documentation (https://pagedown.rbind.io/#preview-paged-html-documents)?

**Comment by mr-illington** [comment]
No, this was my mistake - I was not following the local web server requirements. Thanks for your help.

**Comment by mr-illington** [comment]
Hi again RLesur, 

Just got back to this and still slightly confused. I have xaringan "Infinite Moon Reader" running as an addin in Rstudio and can now preview in the viewer which is a nice feature, but not quite what I was looking for. 

The documentation says: "The easiest way to preview these HTML pages **in a web browser**", but I continue to have the same issue as described earlier. 

One thing I am not doing according to the [xaringan::inf_mr()](https://yihui.name/en/2019/02/ultimate-inf-mr/) doc is 

> run the “Infinite Moon Reader” addin in RStudio, or xaringan::inf_mr() **on an R Markdown document that has the output format xaringan::moon_reader**

Specifically, I can change the output format to `xaringan::moon_reader` but then I loose the `pagedown::thesis_paged` template - so I don't quite see how to keep both. 

May main concern is being able to print consistently to pdf at the end of the thesis. Ironically this is working from MS Edge browser and my old IE browser which I never use, but I thought I'd mention the issue again as I still cannot load the final html in Firefox or Chrome which is more stable in my view.

**Comment by RLesur** [comment]
Hi @mr-illington,

The `xariangan::moon_reader()` output format is for building a slideshow with the **xaringan** package. That's why you loose the `pagedown::thesis_paged` template.

When you run the Infinite Moon Reader addin in RStudio, you should get a log in the R console like this one:

```
Output created: thesis.html
To stop the server, run servr::daemon_stop(1) or restart your R session
Serving the directory /path/to/directory at http://127.0.0.1:4321/thesis.html
```
Note the url at the very end of this message (the url begins with `http://127.0.0.1:...`).  
Now, open this url in Chrome.

In order to print to pdf, you also can use the `pagedown::chrome_print()` function.
