### ISSUE TITLE
Adding bibliography from .bib file in resume?

### ISSUE THREAD

**Issue by filippogambarota** [rstudio/pagedown#148]
Could it be possible to add our publications from a `.bib` file?

**Comment by RLesur** [comment]
This is a very interesting question. Thanks!  

After thinking about it, I would adopt the following strategy:
- parse the `.bib` file in a data frame using the [**bib2df** package](https://github.com/ropensci/bib2df)
- use a chunk (with chunk options `echo=FALSE` and `results='asis'`) to generate the markdown content from the previous data frame

**Comment by filippogambarota** [comment]
> This is a very interesting question. Thanks!
> 
> After thinking about it, I would adopt the following strategy:
> 
> * parse the `.bib` file in a data frame using the [**bib2df** package](https://github.com/ropensci/bib2df)
> * use a chunk (with chunk options `echo=FALSE` and `results='asis'`) to generate the markdown content from the previous data frame

Thanks! Is a wonderful solution I'll surely try it. I think that an integration between the `pagedown` resume and some advanced features similar to the `vitae` package could be very useful. Pagedown offer the advantage to have also the html version for having an online cv.

**Comment by yihui** [comment]
@filippogambarota I definitely agree with you. It will be nice to have a helper function in this package to read a `.bib` file and list all publications automatically on the CV. This is probably not very hard.

BTW, I'm not sure if you have seen @nstrayer's amazing post:  https://twitter.com/NicholasStrayer/status/1181254905018761216 It basically extended your idea further, and all CV data is read from a CSV file.

**Comment by arronlacey** [comment]
I don't know if this helps you at all, but I've got good results doing this:

```
---
title: "My CV"
author: Me!
date: "`r Sys.Date()`"
bibliography: myrefs.bib
csl: academy-of-management-journal.csl
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---
```

```
### Selected Publications

---
nocite: '@*'
---

My University

UK

present - 2011
```
Pair up with some custom .csl files from https://www.zotero.org/styles and it looks pretty good and indented just like the other resume sections
