### ISSUE TITLE
Skip location requirement while including date

### ISSUE THREAD

**Issue by tjbencomo** [rstudio/pagedown#151]
Thank you for developing this great package! It saves me from dealing with Latex. I was wondering if there's a way to hide the location for certain sections. In the example resume, this would mean removing "Qingdao, China"  so it looks like the paper citation below

<img width="493" alt="Screen Shot 2019-11-08 at 9 51 26 PM" src="https://user-images.githubusercontent.com/26121995/68523730-fef12d00-0271-11ea-8c3f-ca5b0a8a3ce8.png">

Unfortunately when I try to remove the location and leave the date, the date shifts to the location spot. If I remove both, the formatting for the sections below go wacky.

<img width="519" alt="Screen Shot 2019-11-08 at 9 56 05 PM" src="https://user-images.githubusercontent.com/26121995/68523774-98204380-0272-11ea-90d5-21d46fc8eba1.png">

Is there a solution to that doesn't require the location but still places the date on the left?

**Comment by cderv** [comment]
I think you can do what is included in the doc for [resume](https://pagedown.rbind.io/#resume)

> The description, location, and time period can each be N/A if the relevant information is not available.

With the example of the template for resume 

```r

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Beijing University of Chemical Technology

B.S. in Information and Computing Sciences

N/A

2010

Thesis: Dyadic wavelet and its application in edge detection
````

Will suppress the location but keep the date at the right place.

Did you try already ?

**Comment by tjbencomo** [comment]
Ah, I missed that in the documentation. That works, thanks for the help!
