### ISSUE TITLE
pagedown::html_resume pagebreak issue

### ISSUE THREAD

**Issue by RyanEckert** [rstudio/pagedown#153]
I'm having an issue with pagebreaks which I believe is different than previously reported issues.
It seems that after page 3 of the resume template, sections stop splitting across pages so that the end bullets of the block do not print and it skips to the next defined section.

I've attached photos to try and illustrate this issue:

Here is a section that is on page 2-3, which prints across the page break as expected:

![Screen Shot 2019-11-12 at 12 48 48 PM](https://user-images.githubusercontent.com/32499745/68696843-b2e10980-054b-11ea-82ac-cea110f0689b.png)

Here is the issue in question, where the continuation of the "Awards" section does not print on the next page:

<img width="586" alt="Screen Shot 2019-11-12 at 2 47 40 AM" src="https://user-images.githubusercontent.com/32499745/68697026-081d1b00-054c-11ea-888f-09579a5e6dca.png">

Has anyone else experienced this?
Is there a potential fix that could be added in the CSS file, other than forcing sections to begin on a new page?

**Comment by RLesur** [comment]
I experienced this kind of overflow.

I've just introduced (https://github.com/rstudio/pagedown/commit/d3b2100313f41bb42a8939a1bc5f2726013e522b) the support for pagebreaks in **pagedown** using the new pandoc filter available in **rmarkdown 1.16** (see https://github.com/rstudio/rmarkdown/pull/1626).

You can try with the development version of **pagedown**:

```r
remotes::install_github("rstudio/pagedown")
```

The documentation about pagebreaks is here: <https://pagedown.rbind.io/#page-breaks>.
