### ISSUE TITLE
travis fails to deploy to gh pages

### ISSUE THREAD

**Issue by RLesur** [rstudio/pagedown#154]
@yihui I've noticed that the two latest travis builds have failed to deploy to gh-pages:  

- [travis build #393 is OK](https://travis-ci.org/rstudio/pagedown/builds/611891324#L1269-L1355)
- there is a fatal error `bad config line 1 in file /home/travis/.gitconfig` with  
[travis build #394](https://travis-ci.org/rstudio/pagedown/builds/612092979#L1138) and [travis build #395](https://travis-ci.org/rstudio/pagedown/builds/612596155#L1432)

The git configuration file <https://xran.yihui.name/.gitconfig> seems to be correct. I don't understand what is the problem.

**Comment by RLesur** [comment]
fixed by https://github.com/rstudio/pagedown/commit/0907291c8f3389671645757f29ca88d3e2beda5a and https://github.com/rstudio/pagedown/commit/8fa63601a29fc131ebacf5dd1e0e212d744d8654

I haven't noticed that your personal domain has changed.

**Comment by yihui** [comment]
In [.travis.yml](https://github.com/rstudio/pagedown/blob/master/.travis.yml), I should have used `curl -L` so that `curl` can follow the redirect. Thank you!
