### ISSUE TITLE
Add support for Edge with Chromium in find_chrome

### ISSUE THREAD

**Issue by cderv** [rstudio/pagedown#160]
As discussed with @RLesur, New Edge browser is [[officially out](https://support.microsoft.com/fr-fr/help/4501095/download-the-new-microsoft-edge-based-on-chromium) and it is based on Chromium now, offering the Chrome Devtools Protocol - same one as in Chrome or Chromium headless. 

Here are some ressources on this new version: 

* [Edge Devtools on Chromium](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium)
* [Edge Devtools Protocol same as Chrome Devtools protocol](https://docs.microsoft.com/en-us/microsoft-edge/devtools-protocol-chromium)
* [puppeteer can be used](https://docs.microsoft.com/en-us/microsoft-edge/puppeteer) 

I tested that it works with `crrri`, our R 📦 for interfacing with chrome devtools protocol in browser. 

Then I tested with `pagedown::chrome_print` and it works perfectly find just by changing the binary

```r
Sys.setenv(PAGEDOWN_CHROME = "C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe")
pagedown::chrome_print("https://pagedown.rbind.io/", output = "pagedown.pdf")
```

First good news: `pagedown::chrome_print` works find with new Edge ! 🎉 

For all those who can't have access to chrome or chromium on their computer, but have Edge in the newer version, it could be nice to support Edge browser in find_chrome or at least mention in the doc it works with Edge Chromium. 

The logic could be: 
* Find chrome on windows
* If not found find Edge and check the version to see if it supports chromium

🤷‍♂  Or there could be a `pagedown::edge_print` with a `find_edge` ? 😉 😄

**Comment by dickoa** [comment]
Hi @cderv,

We can also add the [Brave browser](https://brave.com/) to the list of browser we can support, it's also based on Chromium. 
Thanks

**Comment by cderv** [comment]
Thanks @dickoa . 
Did you try to print a pdf using `chrome_print` with this browser ? Does it work out of the box ?

**Comment by dickoa** [comment]
I tried this  command on Linux and it worked perfectly

```r
Sys.setenv(PAGEDOWN_CHROME = "/usr/bin/brave")
pagedown::chrome_print("https://pagedown.rbind.io/", output = "pagedown.pdf")
```

I just hope that it didn't use my Chromium install I also have on my machine.

**Comment by cderv** [comment]
Cool ! Great News ! 👍 
Thank you !

**Comment by RLesur** [comment]
I don't have access to a Windows computer with the new Edge.  
Is someone interested in writing a PR?

**Comment by cderv** [comment]
I have one but I did not found time yet. If anyone would do it in the meantime, that is great !
