### ISSUE TITLE
Is it possible to ignore N/As when spacing entries?

### ISSUE THREAD

**Issue by mrajeev08** [rstudio/pagedown#161]
I.e.

```
### Header 3

N/A

N/A

N/A
```

vs.

```
### Header 3

Some description

Some place

Some year
```

Results in `### Header 3` having extra empty lines (or padding issue?) below it.

![Screen Shot 2020-01-21 at 6 38 39 PM](https://user-images.githubusercontent.com/42722106/72852678-5140c800-3c7d-11ea-9324-2b2601024cfa.png)

Any way to not include empty line or space for N/As?

**Comment by RLesur** [comment]
@mrajeev08  Thanks for the report!
