### ISSUE TITLE
Multipages tables not supported

### ISSUE THREAD

**Issue by tvroylandt** [rstudio/pagedown#162]
Hello,

The tables in pagedown breaks when you try to display them on multiples pages. 
Here is an example, made with `gt` but i think it's the same with other tables packages.

The default setting could be override by a break-inside : avoid; (as in my example) but it doesn't solve all the problems.

One solution could be to force automatically split the table to print in fact multiples tables with the same style.

    ---
    title: "Test"
    output: 
      pagedown::html_paged
    ---
    
    ```{r setup, include=FALSE}
    knitr::opts_chunk$set(echo = FALSE)
    
    library(tidyverse)
    library(gt)
    ```
    
    ```{css}
    .gt_table{
      break-inside: avoid;
    }
    ```
    
    ```{r}
    # this one is ok
    iris %>% 
      filter(Species == "setosa") %>% 
      select(Species, Sepal.Length) %>% 
      head(10) %>% 
      gt() 
    
    # this one is too long
    iris %>% 
      filter(Species == "setosa") %>% 
      select(Species, Sepal.Length) %>% 
      head(20) %>% 
      gt()
    
    # this one is too large and too long
    iris %>% 
      filter(Species == "setosa") %>% 
      head(20) %>% 
      gt()
    ```

You can experiment it with a template here by removing the `head(20)` at line 124 : https://github.com/tvroylandt/sgdf_pagedown/blob/master/example_pagedown.Rmd

Thank you !

**Comment by jdbarillas** [comment]
This is the code that I used, found here https://gitlab.pagedmedia.org/tools/pagedjs/issues/84,  to split my `gt` tables:

```
// Repeat table headers
// from https://gitlab.pagedmedia.org/tools/pagedjs/issues/84
class RepeatingTableHeaders extends Paged.Handler {
  constructor(chunker, polisher, caller) {
    super(chunker, polisher, caller);
  }
  
  afterPageLayout(pageElement, page, breakToken, chunker) {
    // Find all split table elements
    let tables = pageElement.querySelectorAll("table[data-split-from]");
    
    tables.forEach((table) => {
      // Get the reference UUID of the node
      let ref = table.dataset.ref;
      // Find the node in the original source
      let sourceTable = chunker.source.querySelector("[data-ref='" + ref + "']");
      // Find if there is a header
      let header = sourceTable.querySelector("tbody");
      if (header) {
        // Clone the header element
        let clonedHeader = header.cloneNode(true);
        // Insert the header at the start of the split table
        table.insertBefore(clonedHeader, table.firstChild);
      }
    });
    
  }
}

Paged.registerHandlers(RepeatingTableHeaders);
```

You can save that into a `.js` file and call it as an external script or add it inline to the Rmd document

**Comment by tvroylandt** [comment]
This is nice, thanks !

Could we add this to `pagedown` directly maybe ? @RLesur ?

**Comment by RLesur** [comment]
@tvroylandt Of course, PRs are welcome!

**Comment by felipecrp** [comment]
The paged.js developers are rewriting the table chunker to handle this issue. However, I think it is worth a temporary solution, based on complementary javascript code (paged.js plugin/extension).

**Comment by adrian-the-git** [comment]
Anyone curious why @jdbarillas' solution isn't working should note that the lines:

```js
// Find if there is a header
      let header = sourceTable.querySelector("tbody");
```

...ought to read `"thead"` :)
