### ISSUE TITLE
Allow to add several universities for the same degree for resume

### ISSUE THREAD

**Issue by YonghuiDong** [rstudio/pagedown#166]
What I would like to do is to add several universities for the same degree:

`### University One          Location 1`
`### University Two          Location 2`
`### University Three        Location 3`
`BS in xxx`
`Year`
`Arbitrary content`

Is it possible to do in in pagedown?

**Comment by RLesur** [comment]
I would do something like that:

    ```{js, echo=FALSE}
    Paged.registerHandlers(class extends Paged.Handler {
      constructor(chunker, polisher, caller) {
        super(chunker, polisher, caller);
      }
      beforeParsed(content) {
        const locationBreaks = content.querySelectorAll('.location br');
        for (const br of locationBreaks) {
          const icon = document.createElement('i');
          icon.className = 'fa fa-map-marker-alt';
          br.parentNode.insertBefore(icon, br.nextSibling);
        }
      }
    });
    ```
    
    Education {data-icon=graduation-cap data-concise=true}
    --------------------------------------------------------------------------------
    
    ### University One <br> University Two <br> University Three
    
    BS in xxx
    
    Location 1 <br> Location 2 <br> Location 3
    
    Year
    
    Arbitrary content

**Comment by YonghuiDong** [comment]
Thanks a lot!
