### ISSUE TITLE
pagedown example with equation xref?

### ISSUE THREAD

**Issue by phaustin** [rstudio/pagedown#169]
Can someone point me to an example of how to label and crossreference equations with pagedown?  My first naive attempt:

https://github.com/phaustin/pagedown/blob/eqnums/inst/examples/index.Rmd#L853

doesn't produce an equation number.

**Comment by RLesur** [comment]
`pagedown::html_paged` output format inherits **bookdown** cross-references features.  
Therefore, in order to cross-reference equations, please [see the bookdown documentation](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations).

**Comment by phaustin** [comment]
thanks, that's what I was looking for.
