### ISSUE TITLE
[FR] PDF bookmarks

### ISSUE THREAD

**Issue by shrektan** [rstudio/pagedown#174]
Pagedown is great to have the TOC. However, for long reports, the user still prefers the bookmark because they are able to go to different sections directly,  without having to return to the TOC first, again and again.

So my feature request is: I hope pagedown can generate the bookmarks as the LaTeX [hyperref](https://www.ctan.org/pkg/hyperref) does.

### Now pagedown generates TOC without bookmarks

<img width="850" alt="image" src="https://user-images.githubusercontent.com/8368933/80399970-ac253380-88ec-11ea-920b-236895fe8e80.png">

### LaTeX is able to generate bookmarks

<img width="830" alt="image" src="https://user-images.githubusercontent.com/8368933/80400124-ef7fa200-88ec-11ea-973a-5cb7a3ea7993.png">

**Comment by RLesur** [comment]
I agree with you, it would be great to have this feature.

For now, the PDF is created by Chrome. Outline is still a missing feature in Chrome PDF generation, see the related issues in the Chromium project: [here](https://bugs.chromium.org/p/chromium/issues/detail?id=781797) and [here](https://bugs.chromium.org/p/chromium/issues/detail?id=840455).

In order to add bookmarks/outline, we should post-process Chrome's PDF. AFAIK, it is possible: 

- with Ghostscript using [pdfmark](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdfmark_reference.pdf), see [this post](https://thechriskent.com/2017/02/13/applying-pdfmark-to-pdf-documents-using-ghostscript/) for instance (more tutorials are available online).

- using Node.js [pdf-lib](https://www.npmjs.com/package/pdf-lib) package. This library is used by the Paged.js project in its [pagedjs-cli](https://gitlab.pagedmedia.org/tools/pagedjs-cli/) tool.

I hadn't had time to investigate further. If someone can help, let us know!

**Comment by shrektan** [comment]
I have just tested pdfmark for a while, which is not diffiult to use. I think I can help on this. 

However, I need to know the TOC data in advance. I mean, I need to know which section is referring to which page in order to prepare the configure file for pdfmark. 

It looks like magic for me that pagedown is able to generate the TOC with proper page references. And I have no idea at all about how pagedown works for this and where to find the data I need.

Would you two @yihui @RLesur  mind to give me some hints?

Thanks a lot.

**Comment by RLesur** [comment]
IMO, the most reliable way to obtain the TOC and the page numbers for the TOC entries is through JavaScript. 

I would try to do the following thing:

- using JS, get the TOC entries and their page numbers, build a JSON object with these informations. This script would be called in the [`PagedConfig.after()` function](https://github.com/rstudio/pagedown/blob/b93f46fc1ad70182e5dd3d9fc843f752fd12f780/inst/resources/js/config.js#L49)

- send this JSON object to the R session when printing to PDF like https://github.com/rstudio/pagedown/commit/179e91cc5ea5407325a3800c4c360614fe84bc0f. When received by R, build a similar R object with TOC entries and page numbers

- assign this object in the [`token` environment](https://github.com/rstudio/pagedown/blob/b93f46fc1ad70182e5dd3d9fc843f752fd12f780/R/chrome.R#L179) and attach it as an attribute of the [returned value](https://github.com/rstudio/pagedown/blob/b93f46fc1ad70182e5dd3d9fc843f752fd12f780/R/chrome.R#L201) of `chrome_print()`

After that, I think the ghostscript end is more easy (build the pdfmarks and post process the pdf).

**Comment by RLesur** [comment]
Since I'm familiar with Paged.js, I wrote the JS end that can be called in the `PagedConfig.after()` function:

```js
// from https://stackoverflow.com/q/21647928
const toUTF16BE = x => {
  let res = '';
  for (i=0; i < x.length; i++) {
    let hex = x.charCodeAt(i).toString(16);
    hex = ('000' + hex).slice(-4);
    res += hex
  }
  res = 'feff' + res ;
  return res;
}

const findPage = el => {
  while (el.parentElement) {
    el = el.parentElement;
    if (el.getAttribute('data-page-number')) {
      return parseInt(el.getAttribute('data-page-number'));
    }
  }
  return null;
};

const tocEntriesInfos = ul => {
  const tocEntries = ul.children; // tocEntries are 'li' elements
  let result = []; // where we store the results
  
  for (const li of tocEntries) {
    // get the title and encode it in UTF16BE (pdfmark is encoded in UTF16BE)
    const title = toUTF16BE(li.querySelector('a').textContent);
    
    // get the page number
    const href = li.querySelector('a').getAttribute('href');
    const el = document.querySelector(href);
    const page = findPage(el);
    
    // get the children
    let children = [];
    if (li.querySelector('ul')) {
      children = tocEntriesInfos(li.querySelector('ul'));
    }
    
    result.push({
      title: title,
      page: page,
      children: children
    });
  }
  
  return result;
};
```

the `tocEntriesInfos()` function can be called like that in `PagedConfig.after()`:

```js
  window.PagedConfig.after = (flow) => {
    // ...
    const tocList = flow.source.querySelector('.toc > ul');
    const tocInfos = tocEntriesInfos(tocList);
    // ...
  };
```

**Comment by shrektan** [comment]
Thank you so much. You even wrote the UTF16BE converter :D 

I'll try to build a proto based on this.

**Comment by shrektan** [comment]
Just to update that I've built a proto for pagedown and it looks really good. 

Many thanks to @RLesur 's JS code, as I just need to put the code into the right place and write a simple converter that can translate the TOC object to the correct pdfmark's setting format (as the title has already been encoded under UTF16BE, it's much easier).

 I'll try to file a PR in the following days.

**Comment by datawookie** [comment]
Hi @shrektan, thanks so much for implementing this feature. I was wondering whether I'm doing something wrong.

I specify `outline = TRUE` and the resulting document has thumbnail images of all of the pages in the document.

![image](https://user-images.githubusercontent.com/6134409/143880846-9d8691a4-2925-4ad4-b2ea-bfe9222bef44.png)

This is a very handy feature and I'm very happy with it. However, based on the discussion above, I was expecting to see an outline reflecting the section hierarchy in the document. I'm using the `evince` PDF viewer on Linux and this is what the Bookmarks tab looks like: empty. I've tried Acrobat as well and it also only shows the thumbnails.

![image](https://user-images.githubusercontent.com/6134409/143881139-87f88d17-e5d6-49b8-afa7-bf91918ffabc.png)

Is it possible to get the section headings in the outline too? I'd be prepared to sacrifice the thumbnails in favour of the headings.

Thanks, Andrew.

**Comment by shrektan** [comment]
@datawookie Hi, I'm confused. You should expecting something like below, instead of thumbnails. 

![](https://user-images.githubusercontent.com/8368933/80400124-ef7fa200-88ec-11ea-973a-5cb7a3ea7993.png)

**Comment by datawookie** [comment]
Hi @shrektan,

Okay, thanks! Actually just knowing that you were confused too was very helpful.

I found the problem. I'm using a custom function for the `output_format` parameter.

```r
rmarkdown::render(
  input = "bar.Rmd",
  output_file = "bar.html",
  output_format = "recommend"
)
```

Now when I render straight from RStudio I get the outline text.

But when I render from script I don't.

The reason was that the custom output format function, `recommend()`, didn't include the `toc = TRUE` and `self_contained = FALSE` options.

Popped those in and now I get the text outline. Thanks for your help!
