### ISSUE TITLE
'with_temp_loop' is not an exported object from 'namespace:later'

### ISSUE THREAD

**Issue by saleemakhtar1** [rstudio/pagedown#178]
```
pagedown::chrome_print(input = path, output = "scorecard.pdf", wait = 10, verbose = T)
```

> Using the browser "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
> Trying to find headless Chrome in 20 attempts
> Headless Chrome found at attempt 1
> Error: 'with_temp_loop' is not an exported object from 'namespace:later'
> Closing browser
> Cleaning browser working directory

I've updated **later** to the latest version and still get this error. Are these packages no longer compatible?

**Comment by RLesur** [comment]
This is weird because `later::with_temp_loop()` [still exists](https://github.com/r-lib/later/blob/1f7de5813cd68eb12c74ae9a52e8caeead665b72/NAMESPACE#L15).  
Please, could you post your session infos (`xfun::session_info("pagedown")`)?

**Comment by saleemakhtar1** [comment]
> 
> 
> This is weird because `later::with_temp_loop()` [still exists](https://github.com/r-lib/later/blob/1f7de5813cd68eb12c74ae9a52e8caeead665b72/NAMESPACE#L15).
> Please, could you post your session infos (`xfun::session_info("pagedown")`)?

Apologies, this is my bad. I checked the version number of **later** and it wasn't actually the latest, the update might have failed. Now that I'm updated this is fine. Thanks!
