### ISSUE TITLE
Figure and table numbering format in JSS template is different

### ISSUE THREAD

**Issue by gglee4ai** [rstudio/pagedown#184]
I am trying to JSS template as a preliminary paper, and found that the numbering of figure in pagedown JSS template includes the section number.
Ex). Figure 3.1 (section number 3 is included)
In my humble opinion, the numbering format should be corrected according to the JSS format, or the hard-code tips should be provided. 
Thanks in advance for your effort and package!

**Comment by RLesur** [comment]
Thanks a lot for the report! This is now fixed in the development version.  
Sorry for the delay!
