### ISSUE TITLE
Create output file with the current date in its name

### ISSUE THREAD

**Issue by martinschmelzer** [rstudio/pagedown#187]
Correct me if I am mistaken:

The only way bookdown (and therefore pagedown) is able to auto append the current date to the output file is to use an anonymous functio nin the YAML header:

```
---
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_file = paste0(
        xfun::sans_ext(basename(input)), '-', Sys.Date(), '.html'
      ),
      envir = globalenv()
    )
  })
---
```

I created a report template using pagedown. It boiled down the previous reporting process from approx. 3 hours of work (using Excel (booo), SQL and PowerPivot) down to 3 minutes. I want to make the template as user friendly as possible so that non-R cracks like my colleagues (sorry guys) wont get confused by being confronted with that kind of ugly YAML header.

Is there another option? I fiddled with the `post_processer` of knitr but that made the captioning not work anymore.

**Comment by cderv** [comment]
This `knit` field will allow the knitr button in RStudio to use your function. You can also put this function in a 📦 so that it is less cryptic
```yaml
knit: mypkg::render_report
````

> I fiddled with the post_processer of knitr but that made the captioning not work anymore.

Yes I think you can manage to do that if you create a custom format that will append the date in the post processor step to the `output_file` . Look at `?output_format`. You when then use your custom format in your Rmd file 
```yaml
output: mypkg::my_format
```

Do you want this appending to always happen ?

**Comment by martinschmelzer** [comment]
I was hoping to manage this internally. I could create that function in my custom format and add this function in the YAML. My goal though is to omit the `knit` parameter completely.

As I said, using `post_processor` works, but messes up the captioning of figues and tables done by `bookdown`.

If this is managable internally, inside my custom format, then it would be easy to turn this on or off.

**Comment by cderv** [comment]
> As I said, using post_processor works, but messes up the captioning of figures and tables done by bookdown.

This is supprising - it should not. 

Did you take care of calling bookdown post processor function inside your post processor ? Your post processor should not replace the one from bookdown but act in addition to it. There are examples of this in various R packages that create formats based on others.

If you can share the code of your format, I can guide you.

**Comment by martinschmelzer** [comment]
That is a point I did not take notion of. I will check it out.

**Comment by cderv** [comment]
Here is an example from bookdown 

https://github.com/rstudio/bookdown/blob/57f1217c20835d538d103244ea46ec65acc374c3/R/html.R#L63-L65 

If it can help... 

Let me know if it works !

**Comment by martinschmelzer** [comment]
I tried fiddling with it and the examples. No luck. Theres is something I am missing I guess. This is the code for my format:

```
custom_report <- function(css = tmpl_resource("template", "resources", "custom.css"),
                       template = tmpl_resource("template", "resources", "template.html"),
                       self_contained = TRUE,
                       number_sections = TRUE,
                       toc = TRUE,
                       workOnly = TRUE,
                       ...) {
  
  custom_format <- pagedown::html_paged(
    toc = toc,
    css = css,
    template = template,
    self_contained = self_contained,
    number_sections = number_sections,
    ...
  )

  # this is the bookdown post_processor I guess?
  defPostProcessor <- bevaktuell_format$post_processor
  
  # change it
  custom_format$post_processor <- function(metadata, input_file, output_file, clean, verbose) {
    if(is.function(defPostProcessor)) output <- defPostProcessor(metadata, input_file, output_file, clean, verbose)
    fileName <- paste0(xfun::sans_ext(output), '_',
                       gsub("-", "", Sys.Date()), '.',
                       xfun::file_ext(output))
    
    return(fileName)
  }
  
  return(custom_format)
}
```

**Comment by cderv** [comment]
Not sur to have completly understood what you are trying to do.

> # this is the bookdown post_processor I guess?
>  defPostProcessor <- bevaktuell_format$post_processor

What is  bevaktuell_format  ? 

> As I said, using post_processor works, but messes up the captioning of figures and tables done by bookdown.

How is bookdown involved in this ? How do you use it with pagedown ? I don't see any bookdown mentions here.

_(As a reminder for such questions in the future, you should prefer https://community.rstudio.com, GH issue are for issues and Feature request regarding the package. The community is large and several people can share and help on such use case)_

**Comment by martinschmelzer** [comment]
That was a typo. Fixed it above.

From what I read, `bookdown::html_document2` is the base format for `html_paged`. I just wnat to have the output file name in the format [INPUTFILENAME]_[currentDate].html

Sorry for misusing this board.

**Comment by cderv** [comment]
> From what I read, bookdown::html_document2 is the base format for html_paged.

Oh I see ! I thought you were calling bookdown on your own code. Sorry, I should have reminded that. 

I think your are very close and just you did not completly understand the post processor step. It happens **after** pandoc conversion. In the function, `output_file` is the path to the output file from pandoc that exists on the disk. So you just need to create a copy or rename it with you new file name. Currently you are just returning the new path of a file that does not exist. 

If you add 
```r
    file.rename(output, fileName)
```  
before 
```r
return(fileName)
``` 
It should work as expected.

**Comment by martinschmelzer** [comment]
Un, wait for it, believable -.-'

That is a new level of misunderstanding for myself. Thanks fo your support, it works.

**Comment by cderv** [comment]
Is this type of solution ok for what you want to do ? 
Can we close this ?

**Comment by martinschmelzer** [comment]
Yeeeees. Close it!
