### ISSUE TITLE
Allow to use chrome_print on parametrized Rmarkdown document 

### ISSUE THREAD

**Issue by cderv** [rstudio/pagedown#188]
From a question in the community : https://community.rstudio.com/t/not-able-to-produce-paged-pdf-document-when-trying-to-render-html-paged-rmarkdown-document-using-parameters/80677/2

Current you can render a Rmd file using 
```r
pagedown::chrome_print("reprex.Rmd")
```
but the included rendering does not accept params as in :

```r
rmarkdown::render("reprex.Rmd", params=list(test="html"))
```

@yihui @RLesur How about we support that by 
* taking `...` in `chrome_print` to pass to `render` : `pagedown::chrome_print("reprex.Rmd", params = list(test="html"))`
* or by adding a `render_args` argument taking a list to match `render` argument ?  `pagedown::chrome_print("reprex.Rmd", rmd_args = list(params = list(test="html")))`

**Comment by yihui** [comment]
The `chrome_print()` function actually also accepts `.html` input, so this should work:

```r
pagedown::chrome_print(
  rmarkdown::render("reprex.Rmd", params=list(test="html"))
)
```

I'm fine with adding `...` or `render_args`, but it doesn't seem to save a lot of typing effort. The solution I mentioned is totally flexible and you can use any arguments of `rmarkdown::render()`.

**Comment by cderv** [comment]
Oh I see. You are passing the all command to `chrome_print` because it knows how to render html file and `render` returns the output path... I missed that. 

Is this documented ? 

Anyway, I'll answer that in the community and we'll how it received (simple or too verbose)

**Comment by cderv** [comment]
Yes this is what I answered in the [community post ](https://community.rstudio.com/t/not-able-to-produce-paged-pdf-document-when-trying-to-render-html-paged-rmarkdown-document-using-parameters/80677/2)

```r
output <- rmarkdown::render("reprex.Rmd", params=list(test="html"))
pagedown::chrome_print(output)
```

That works well. 

We could also just document that explicitly and consider it simpler to maintain that adding a new parameter to do the same.

**Comment by yihui** [comment]
Okay. I just added more documentation. Thanks!
