### ISSUE TITLE
vectorized high-resolution plots?

### ISSUE THREAD

**Issue by AlvaroMCMC** [rstudio/pagedown#196]
I copied some code from another Rmardownfile which rendered the pdf with optimal resolution:

1) pdf Rmardown-rendered using latex.

![image](https://user-images.githubusercontent.com/21317475/97518415-1c2c7900-1965-11eb-91a2-512df7ca97e5.png)

2) pdf pagedown-html-rendered:

![image](https://user-images.githubusercontent.com/21317475/97518479-3fefbf00-1965-11eb-8b81-7040d608ba6b.png)

Is there a way to let pagedown fix this? (to be like the first option)

**Comment by RLesur** [comment]
Hi @AlvaroMCMC !

Please, could you post a reproducible example? Without a reproducible example, we cannot help you.

Thanks a lot!

**Comment by AlvaroMCMC** [comment]
Hi @RLesur , thank you for taking the time to answer. Before I post the reprex. I could change the image resolution with dpi:

````
```{r, dpi=600}

plot_grepel_0 +
  geom_segment(data = data_metales_2, aes(x = ESTE, y = NORTE, xend = X, yend = Y), color = "gray", size = 0.2, alpha = 0.7) +
  sub_grobs

```
````

My question is:
Is there a way not to render plot as image but as a vectorized image (not raster) as when you render with latex?

**Comment by RLesur** [comment]
Thanks but I cannot reproduce your code example (`plot_grepel_0` is an unknown object in a fresh R session).

Technically, your question is related to the **knitr** package. Maybe could you try one of the recipes presented here: <https://bookdown.org/yihui/rmarkdown-cookbook/graphical-device.html>, particularly `dev= "svg"`.

**Comment by AlvaroMCMC** [comment]
It worked, thanks
