### ISSUE TITLE
How to adjust margin properly?

### ISSUE THREAD

**Issue by AlvaroMCMC** [rstudio/pagedown#197]
I am generating a pdf, but the margin of page are not displayed properly,

This is my reproducible code

```
---
title: "A Multi-page HTML Document"
author: "Yihui Xie and Romain Lesur"
date: "`r Sys.Date()`"
output:
  pagedown::html_paged: default
  pagedown::html_paged():
    toc: yes
    self_contained: no
knit: pagedown::chrome_print
css: custom-page.css
---

<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
  }
  .col3 {
    columns: 3 100px;
    -webkit-columns: 3 100px;
    -moz-columns: 3 100px;
  }
</style>

# Resumen ejecutivo

This is an example of a multi-page HTML document. See https://pagedown.rbind.io for the full documentation. The rest of this document is random text.

## AMC

# Random text

## Put in your css file or directly in rmarkdown


## This section will have three columns

<div class="col3">
**1** one  
**2** two  
**3** three  
**4** four  
**5** five  
**6** six  
**7** seven  
**8** eight  
**9** nine  
</div>

## This section will have two columns

<div class="col2">
```{r}
head(mtcars)
tail(mtcars)
```
</div>
```

This is the custom-page.css

```
/* page size */

@page {
  size: A4 portrait;
  margin: 10mm;
  bleed: 0mm 0mm 0mm 0mm;
  marks: crop cross;
  padding: 0mm;
}

/* store some string variables */
.shorttitle1 {
  string-set: h1-text content(text);
}

.shorttitle2 {
  string-set: h2-text content(text);
}

/* left page */
.running-h1-title {
  position: running(runningH1Title);
  width: var(--running-title-width);
  text-overflow: ellipsis;
  overflow: hidden;
}
.running-h1-title:before {
  content: string(h1-text);
}

@page :first {
  @top-left {
    content: none;
  }
  @top-right {
    content: none;
  }
  @bottom-right {
    content: none !important;
  }
  background-image: var(--front-cover);
  background-position: center;
  background-size: contain;
  background-repeat: no-repeat;
}

@page :left {
  @top-left {
    content: counter(page);
  }
}

@page :right {
  @top-right {
    content: counter(page);
  }
}

/* Front cover */
.front-cover {
  break-after: page;
}

/* page breaks; aka CSS fragmentation */
.level1 {
  break-before: page;
}
.section > h1, .section > h2, .section > h3, .section > h4, .section > h5, .section > h6 {
  break-after: avoid;
}
.footnotes {
  break-before: always;
  break-after: always;
}
.figure {
  break-inside: avoid;
}

/* do not break captions */
caption {
  break-inside: avoid;
  break-after: avoid;
}
```

This is the image: (margin not as expected) 10mm per side
![image](https://user-images.githubusercontent.com/21317475/97526387-fe680f80-1976-11eb-8ea8-d1d655f8369f.png)

**Comment by NewGraphEnvironment** [comment]
@AlvaroMCMC - did you pinpoint a solution for your issue by chance? Running into some margin issues myself....

**Comment by jzadra** [comment]
Me too
