### ISSUE TITLE
Internationalization for "List of abbreviations"

### ISSUE THREAD

**Issue by jtrecenti** [rstudio/pagedown#199]
Hi! thanks for this awesome package

I was trying to use the list of abbreviations tool, but I didn't manage to modify the "List of abbreviations" title.

Digging into it I found that probably the title is hard coded in the `hooks.js` file:

https://github.com/rstudio/pagedown/blob/e7d8b07caef91eea43f1af01b3e439e95def792a/inst/resources/js/hooks.js#L68

Is it possible to modify it some way? I was thinking on a `loa-title:` parameter added to the front matter, but I have no idea how to implement it.

Thanks!

**Comment by RLesur** [comment]
Hi @jtrecenti ,

Thanks a lot for the report. This is now fixed.
The `loa-title` option now works with the development version of pagedown:

```r
remotes::install_github("rstudio/pagedown")
```
