### ISSUE TITLE
How to add o modify yaml headers from pagedown template?

### ISSUE THREAD

**Issue by AlvaroMCMC** [rstudio/pagedown#200]
I loaded the thesis template from pagedown. It does not have the yaml headers I would like to have:

Thesis template yaml headers:
```
degree: Master of Documentation
institute: Typeset University
faculty: Reproducibility and FOSS
department: Templates
location: St. Catharines, ON 
date:
```

I would like to have:
```
Age: 
College: 
District:
City: 
date of birth:
```

How do I do it?

**Comment by cderv** [comment]
The YAML field currently in the template are used by Pandoc as variable to fill in the Pandoc's html template used for Thesis output. It is this one: https://github.com/rstudio/pagedown/blob/master/inst/resources/html/thesis.html

If you don't know yet about Pandoc's template, here is a good resource: 
https://bookdown.org/yihui/rmarkdown-cookbook/html-template.html

If you want to have other variables than the default one, you would have to change the template used to a custom one you create. You can then pass this template to `template` argument in `pagedown::thesis_paged()`. 

If you want to do that, I suggest you start by modifying the existing one and keep it up to date in the future if we need to add some fix. 

Is this answering your question ?

**Comment by AlvaroMCMC** [comment]
Yes, It is. Thanks. I think I will just add some "params".

**Comment by cderv** [comment]
Rmarkdown parametrized report is indeed a great way to pass variable inside a document content. 

I'll close this as it was only a question.
