### ISSUE TITLE
html_resume(), 'fig_caption' argument

### ISSUE THREAD

**Issue by nplatonov** [rstudio/pagedown#208]
knitr 1.30 fixed the option `fig_caption = FALSE` for `rmarkdown::html_document()`. Is it possible not to use strict `fig_caption = FALSE` argument in `html_format()` in body of `html_resume()`?

**Comment by yihui** [comment]
It seems you want to use `fig_caption = TRUE`? I just made this argument configurable in `html_resume()`, although I'm not sure if `fig_caption = TRUE` works in this case. The fix https://github.com/yihui/knitr/commit/42b91f01608e573e6c255e3adacf0f75bccdb176 was for `fig_caption = FALSE` and shouldn't affect `fig_caption = TRUE`, so it is probably irrelevant. Thanks!
