### ISSUE TITLE
Extra blank pages

### ISSUE THREAD

**Issue by vidonne** [rstudio/pagedown#209]
We are using the Paged HTML Document template for the [unhcr-report](https://github.com/vidonne/unhcr-report) project but we have a few issue with extra blank page automatically added.

1. There is always one extra blank page between the `frontmatter` and `chapter` section. I haven't included any `break-before` or `break-after` for this in my CSS but can't get rid of it. Does it come included in the package?
2. We set `break-before: left;` for the `back-cover` section but when it is suppose to sit on the left page following the final page with content, it inserts 2 blank pages instead. Is this behavior normal? The other scenario works as expected.

Thanks for your help

**Comment by RLesur** [comment]
Hi @vidonne !

Have you also tried with the development version of pagedown? #202 should have fixed that.

**Comment by vidonne** [comment]
@RLesur indeed it removed the extra blank pages but now there is no more page by list e.g. 1 page for the table of content, 1 for list of figures, etc. 
<img width="533" alt="all_lists" src="https://user-images.githubusercontent.com/1830612/105736454-1844ce80-5f35-11eb-95c0-465e385d1b11.png">

Same for the `<h1>` they don't create page break by default. I guess all of this is easily solve by adding page break to the `<h1>` tag.

Another thing with the update to the new dev version of pagedown it doesn't find anymore the backcover image. See
[Reproducible Analysis_pagedown_dev_v.pdf](https://github.com/rstudio/pagedown/files/5868077/Reproducible.Analysis_pagedown_dev_v.pdf) backcover BG disappeared compare to previous version.

**Comment by vidonne** [comment]
@RLesur trying to fix this I noticed that `break-before: recto` works but when I change it to `break-before: page` it doesn't any idea why?
Also since we upgraded the pagedown version still getting the error of the back-cover image not showing anymore.

**Comment by vidonne** [comment]
Actually I think I know why the back-cover doesn't show it related to the issue [211](https://github.com/rstudio/pagedown/issues/211) as in the default css the back-cover image is called with `.pagedjs_page:last-of-type {background-image: var(--back-cover);}`

**Comment by RLesur** [comment]
> when I change it to break-before: page it doesn't any idea why?

This is odd. I'm pretty confident that `break-before: page` should work.

> Actually I think I know why the back-cover doesn't show it related to the issue 211 as in the default css the back-cover image is called with .pagedjs_page:last-of-type {background-image: var(--back-cover);}

Yes, this is the same issue as #211

**Comment by vidonne** [comment]
> I'm pretty confident that `break-before: page` should work.

FYI couldn't make `break-before` work but oddly `break-after: page` works like a charm. Really weird.

**Comment by RLesur** [comment]
@vidonne With the development version of pagedown, this example works fine for me:

    ---
    title: "Page breaks test"
    date: "`r Sys.Date()`"
    output: pagedown::html_paged
    knit: pagedown::chrome_print
    ---
    
    # Break before test
    
    ::: page-break-before
    this text is on a new page
    :::
    
    # Break after test
    
    ::: page-break-after
    no more text after that
    :::
    
    this text is on a new page

I get this result: 
[page-breaks.pdf](https://github.com/rstudio/pagedown/files/5906693/page-breaks.pdf)

**Comment by RLesur** [comment]
@vidonne any follow up? is your problem solved?

**Comment by vidonne** [comment]
@RLesur yes it's now working. Thanks for your help
