### ISSUE TITLE
Plot duplication

### ISSUE THREAD

**Issue by vidonne** [rstudio/pagedown#210]
When a plot hits the very bottom of the page sometimes instead of moving to the next page it actually gets duplicated see image below. In this example the Rmd contains only one chunk of code to create the chart but it's rendered twice, even include the paragraph before the chart.

<img width="956" alt="Screenshot 2021-01-21 093945" src="https://user-images.githubusercontent.com/1830612/105325512-fbbf3400-5bcc-11eb-802f-ccca8e0a90d1.png">

**Comment by RLesur** [comment]
I haven't experienced this problem with graphs before. I had had a similar issue with headers (#131). 
Could you share the html file and its assets?

**Comment by vidonne** [comment]
Hi Romain,
I created a branch with plot duplication problem you can find all the files [here](https://github.com/vidonne/unhcr-report/tree/plot-duplication) and the [html related](https://github.com/vidonne/unhcr-report/blob/plot-duplication/plot-duplication.html).
Let me know if you need anything else. Thanks for the help

**Comment by RLesur** [comment]
Thanks @vidonne!
I'm embarassed because both the HTML preview and the PDF are fine with my computer.
Here's the PDF file I get: [plot-duplication.pdf](https://github.com/rstudio/pagedown/files/5858063/plot-duplication.pdf)

**Comment by vidonne** [comment]
Weird this it the PDF I get: [plot_duplication.pdf](https://github.com/rstudio/pagedown/files/5865088/plot_duplication.pdf) Page 5-6 you can see the duplication. I haven't updated to the dev version of pagedown though so that's maybe why there is a difference. For some reason I get an error while trying the install.

**Comment by yihui** [comment]
> For some reason I get an error while trying the install.

@vidonne What was the error? Perhaps you can try:

```r
install.packages(
  'pagedown', repos = c(
    rstudio = 'https://rstudio.r-universe.dev',
    CRAN = 'https://cloud.r-project.org'
  )
)
```

**Comment by vidonne** [comment]
@yihui Thanks now installation worked and duplication is gone!!!

**Comment by cderv** [comment]
That is great news ! 

So dev version fixed it, I'll close.
