### ISSUE TITLE
Unable to modify font size of footnotes

### ISSUE THREAD

**Issue by oliviermeslin** [rstudio/pagedown#217]
Hi,

I'm opening this issue because I'm unable to modify the font size of footnotes in `pagedown` using CSS (MWE below). This problem seems to be present for other layout elements (eg, color). 

When I inspect the code of the footnote in the html output document, I always find `font-size: x-small;`, instead of the size I wanted. My best guess is that the Javascript treatment of footnotes in `hooks.js` (lines 294-308) is written in a way that cannot be overriden by CSS specifications.

Is there a simple solution I missed?

------

Here is a MWE:

**Rmd file**

```
---
title: "Test of footnotes"
author: "Daffy Duck"
output:
  pagedown::html_paged: 
    css:
      - style.css
paged-footnotes: true
---

# A first title
## A second title
This is an interesting text.^[This is a footnote.]
```

**Associated CSS `style.css` file**

```

h1  {
  font-size: 40px;
}
h2  {
  font-size: 30px;
}
body {
  font-size: 20px;
}
.footenotes {
  font-size: 30px !important;
  color: yellow !important;
}
.footenote {
  font-size: 20px !important;
  color: red !important;
}
span.footenote {
  font-size: 30px !important;
  color: blue !important;
}
```

**Comment by RLesur** [comment]
Sorry for that, this is not yet documented. There is a typo in the class name: the footnotes `span`s are of class `footnote` and not `footenote`.   
This CSS declaration works well:

```css
.footnote {
  font-size: 20px !important;
  color: red !important;
}
```

I'll update the documentation.

**Comment by RLesur** [comment]
@oliviermeslin I've updated the documentation entry on footnotes, see <https://pagedown.rbind.io/#footnotes>.

**Comment by oliviermeslin** [comment]
Oh, I just realized there's a typo in my style.css (`footenote` instead of  `footnote`)... Sorry for that...
