### ISSUE TITLE
Duplicated abbreviations in the glossary

### ISSUE THREAD

**Issue by linogaliana** [rstudio/pagedown#218]
Hi, 

Having the possibility to put a list of abbrevation is really a nice feature when writing a technical report or a book. However, when putting  the same abbrevation at two different locations, we end up with duplicated entries in the glossary.

For instance, the following document will generate a duplicated entry for UN: 

```r
---
title: "My awesome report"
author: "Bugs Bunny"
output: pagedown::html_paged
---

# My awesome text
  
The 
<abbr title="International Monetary Fund"><b>IMF</b></abbr>
and the 
<abbr title="United Nations"><b>UN</b></abbr> are both international
institutions. Before 
<abbr title="World War II"><b>WW2</b></abbr>, 
the
<abbr title="United Nations"><b>UN</b></abbr>
was denominated as   
<abbr title="League of Nations"><b>LON</b></abbr>
```

This will result in the following glossary

![image](https://user-images.githubusercontent.com/33896139/109853114-d7d42100-7c55-11eb-8af4-51d5bb058c32.png)

We might be interested in avoiding duplicates. I guess the change would be minimal and just require to put somewhere in [hook.js](https://github.com/rstudio/pagedown/blob/master/inst/resources/js/hooks.js#L61-L93), something like a `unique` or a `distinct` call (sorry, I don't know JS at all otherwise I would have proposed the modification involved)

**Comment by RLesur** [comment]
Thanks a lot for the bug report! This is now fixed in the development version of **pagedown**.
