### ISSUE TITLE
Resume template: how to work with a csv file of my experience., ...?

### ISSUE THREAD

**Issue by lennyzhlin** [rstudio/pagedown#220]
I prefer to maintain my experience in a csv file.  The csv file serves as a pool of experience, skills, training, awards, publications, and so on.

I customize my resume by choosing items in the csv file.

**Comment by yihui** [comment]
Please see https://github.com/nstrayer/datadrivencv.

(BTW, although I was aware of this package myself, I tested by googling for "pagedown csv" and it appeared in the third result, so I guess it should be discoverable.)

**Comment by cderv** [comment]
I'll close this as any CSV related feature / questions for pagedown will be better in the other package linked above.
