### ISSUE TITLE
Inline links

### ISSUE THREAD

**Issue by paulcbauer** [rstudio/pagedown#228]
As described here (https://pagedown.rbind.io/#links) it was possible to have inline links in R markdown. They worked/were clickable in html and PDF output.

We just ported our rmarkdown/latex/bookdown working paper template (https://osf.io/q395s) to pagedown (https://osf.io/k8jhx). Is there a way to get back the old inline display of links in pagedown (and not show them as footnotes?)?

**Comment by cderv** [comment]
Links should be converted to footnotes only if you have 
```yaml
links-to-footnotes: true
```
in your YAML header, as the doc you linked to says.

Do you have this in your source Rmd file ? Can you share the source of your Rmd file ?

It is working as expected for me with the default document.

**Comment by paulcbauer** [comment]
@cderv links-to-footnotes: false worked.. sorry we could have discovered by ourselves. Thanks!

(We just updated the source Rmd file accordingly: https://github.com/paulcbauer/Writing_a_reproducable_paper_in_pagedown/blob/main/paper.Rmd)

**Comment by cderv** [comment]
Awesome ! Glad it works now.
