### ISSUE TITLE
Cross referencing figures with `html_letter`

### ISSUE THREAD

**Issue by NewGraphEnvironment** [rstudio/pagedown#234]
First off - unreal package.  Amazing! Game changer.  Thank you so much.

For some reason I cannot seem to cross reference figures with `html_letter`.  I can see that the figure caption will be a pop up in the `html `file but I would prefer it as a caption that I could cross reference in the text.  

Interestingly, I have found a situation where it does work and that seems to be when the actual chunk output does not display. Sorry for the use of the `DiagrammeR` package in the example but it is the exception case I ran into so thought it might be relevant.  Thank you!

```
---
title: "A letter of recommendation for Emi Tanaka"
author: "Yihui Xie"
output:
  pagedown::html_letter:
knit: pagedown::chrome_print
---
Any thoughts on how I might get Figure \@ref(fig:figure-1) to cross-reference like the failed output of Figure \@ref(fig:figure-2) does?

```{r figure-1, fig.cap='my_caption'}
knitr::include_graphics('https://www.rstudio.com/wp-content/uploads/2016/09/RStudio-Logo-Blue-Gray-250.png')
```
```{r figure-2, fig.cap='my_caption2'}
DiagrammeR::grViz("digraph rmarkdown{
graph[layout = dot, rankdir = LR]
d1 [label = 'step 1']
d2 [label = 'Step 2']
d1 -> d2 
}")
```
```

**Comment by RLesur** [comment]
Thanks a lot for this bug report.
This behavior comes from the fact that the `html_letter` output format modifies the defaut value of the `fig_caption` parameter and cannot be changed:
https://github.com/rstudio/pagedown/blob/f63b780204186003054d0364cd6569688f5120a3/R/paged.R#L60-L62

This is undocumented, sorry for that.

**Comment by RLesur** [comment]
This is now fixed in the development version of **pagedown**. You can install this version with:

```r
remotes::install_github("rstudio/pagedown")
```

In order to get figure references in `html_letter` you need to use

```yaml
output:
  pagedown::html_letter:
    fig_caption: true
```

**Comment by NewGraphEnvironment** [comment]
👑
