### ISSUE TITLE
New version duplicates the header of htmlTables even if they begin on next page

### ISSUE THREAD

**Issue by martinschmelzer** [rstudio/pagedown#265]
A document of mine that is rendered monthly broke today after updating pagedown to 0.16.
Take the following MWE:

    ---
    title: "A Multi-page HTML Document"
    author: "Yihui Xie and Romain Lesur"
    date: "`r Sys.Date()`"
    output:
      pagedown::html_paged:
        toc: false
        self_contained: true
    ---
    # Introduction
    
    Test
    
    ```{r, echo = F}
    x <- htmlTable::addHtmlTableStyle(mtcars[1:2,], css.class = "page-break-before")
    htmlTable::htmlTable(x)
    ```

The table header is duplicated even though the table starts and ends on the same page.

![image](https://user-images.githubusercontent.com/7760212/147950565-7ebee9d9-907a-4fc9-890f-b41fb5fc52c8.png)

    ## R version 4.1.0 (2021-05-18)
    ## Platform: x86_64-w64-mingw32/x64 (64-bit)
    ## Running under: Windows 10 x64 (build 19044)
    ## 
    ## Matrix products: default
    ## 
    ## locale:
    ## [1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
    ## [3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
    ## [5] LC_TIME=German_Germany.1252    
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] htmlTable_2.3.0
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] bookdown_0.24     digest_0.6.29     crayon_1.4.2      R6_2.5.1         
    ##  [5] backports_1.4.1   jsonlite_1.7.2    
    magrittr_2.0.1    evaluate_0.14    
    ##  [9] stringi_1.7.6     rlang_0.4.12      rstudioapi_0.13   jquerylib_0.1.4  
    ## [13] bslib_0.3.1       checkmate_2.0.0   rmarkdown_2.11    tools_4.1.0      
    ## [17] stringr_1.4.0     htmlwidgets_1.5.4 xfun_0.29         yaml_2.2.1       
    ## [21] fastmap_1.1.0     compiler_4.1.0    htmltools_0.5.2   pagedown_0.16    
    ## [25] knitr_1.37        sass_0.4.0

**Comment by nplatonov** [comment]
In v0.16, if `knitr::kable()` appears on the top of page, then header is duplicated.

```
---
output: pagedown::thesis_paged
---

_```{r echo=FALSE}
for (i in seq(14)) cat(i,"\n\n")
_```

_```{r example, echo=FALSE, fig.cap="This is a caption"}
knitr::kable(iris)
_```

**Comment by yihui** [comment]
This is most likely due to #250. @felipecrp Do you have an idea? Thanks!

**Comment by felipecrp** [comment]
It is likely a bug on the javascript we got in the paged.js forum. I will try to reproduce the error.

**Comment by felipecrp** [comment]
@yihui I could reproduce the error in one of my reports. The problem seems to happen (to me) only when I open the report with the browser in a zoom greater than 100% (e.g. 150%). When I open without zoom, the header rows apparently do not repeat.

@martinschmelzer Can you test and confirm the behavior?

**Comment by martinschmelzer** [comment]
@felipecrp  Sorry, did not have the time so far. Will try today.

**Comment by martinschmelzer** [comment]
@felipecrp  I cannot confirm that. IN the RStudio Viewer as well as in Firefox, the zoom level does not change anything. The table head stays duplicated.

**Comment by felipecrp** [comment]
@martinschmelzer You need to reset the zoom and reload the document (F5).

**Comment by martinschmelzer** [comment]
@felipecrp  I am not sure  if I misunderstand you. I fiddled with different zoom levels and (hard) refreshed the page. Tried Firefox and Chrome. I do not get rid of the second header, no matter what I try.

**Comment by beatrizmilz** [comment]
@jtrecenti and I have encountered the same issue (the headers are duplicated when the table starts in the begining of the page). An smaller example is the template for thesis:
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/42153618/153657074-8e8cc200-f625-4092-a921-f69bf1a16cfe.png">

**Comment by yihui** [comment]
Please check if #272 has fixed this issue by installing the development version via

```r
remotes::install_github('rstudio/pagedown')
```

Thanks!

**Comment by NewGraphEnvironment** [comment]
This still occurs when there is a table caption that spans multiple lines.  Unfortunately we also cannot see the first lines of the caption on the page before either.  Might be tricky.  Tested on version 0.18.1

![image](https://user-images.githubusercontent.com/46538103/166342309-4fbed1da-649b-4a05-aa05-11322a75ca99.png)
