### ISSUE TITLE
Native chrome automation for PDF creation

### ISSUE THREAD

**Issue by RLesur** [rstudio/pagedown#27]
I want to share an experiment I made with @MilesMcBain's [chradle](https://github.com/MilesMcBain/chradle) test package.
The goal of chradle is to communicate with Chrome through the [Devtools Protocol](https://chromedevtools.github.io/devtools-protocol/) (like puppeteer) using a websocket connection (with [rstudio/websocket](https://github.com/rstudio/websocket)): we have a direct connection between R and Chrome.
I only succeeded with a screenshot.
``` r
# remotes::install_github('milesmcbain/chradle')
library(chradle)

session <- chr_init(url = "https://pagedown.rbind.io/", incomming_debug = TRUE)
resp <- chr_call(session, '{"id":3,"method":"Page.captureScreenshot"}')
img <- jsonlite::base64_dec(resp$result$data)
writeBin(img, 'screenshot.png')
# I didn't succeed with a PDF 
# https://chromedevtools.github.io/devtools-protocol/1-3/Page#method-printToPDF
# state <- chr_call(session, '{"id":4,"method":"Page.printToPDF"}')
chr_kill(session)
chr_clean()
```
I found this test extremely interesting: it shows that a Chrome automation for PDF generation (or other tasks) should be feasible from R but it seems to be a huge task (or a side project).
I think we are in a too early stage to work on this... but maybe in the future.

**Comment by yihui** [comment]
This sounds awesome! Once again you brought something exciting to my attention. I'll take a closer look when I have a chance. Thanks!

**Comment by yihui** [comment]
@cderv Thanks! I wasn't aware of the two projects you mentioned (I only knew puppeteer). For the `processx::run()` approach above, that seems to be what `pagedown::chrome_print()` does: https://github.com/rstudio/pagedown/blob/master/R/chrome.R The real challenge is not how to create the PDF, but creating the PDF with the correct _timing_, i.e., make sure everything has been loaded and all JS libraries have finished processing the DOM. The former problem was addressed by #26 and the latter has a suboptimal solution #22 (this is what I wish to improve with the websocket approach). There is actually a third problem mentioned in #24: how to remove the default headers and footers. This is currently not possible without using the Devtools Protocol (I'm not sure if it is possible with it, either, though).

**Comment by cderv** [comment]
Oh I was not aware of `chrome.R` file. 
It is a very interesting problem. I am curious if `gepetto` approach allows that or not. I will try. 
However, in the long term, I am not sure having a node.js / npm component dependency is viable. websocket approach seems better but tricky.

If I find some time synchronized with your pace with @RLesur and in respect with other project, I will look into it too because it is really interesting! 😉

**Comment by RLesur** [comment]
Thanks @cderv for your interest on this issue!
I also did similar test with decapitated and Chrome CLI and also got disappointing results with `html_paged` documents unless using the `--virtual-time-budget` option.
With puppeteer, I get fine results with this kind of js script:
``` js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://pagedown.rbind.io/html-letter/', {waitUntil: 'networkidle2'});
  await page.waitFor(() => !!document.querySelector('.footnote-area'));
  
  await page.pdf({path: 'letter.pdf', format: 'A4'});
  await browser.close();
})();
```
The trick here comes from the fact that the `footnote-area` class elements are created at the end of the DOM processing.
We could build a more reliable process using [a `window.PagedConfig.after` function](https://gitlab.pagedmedia.org/tools/pagedjs#polyfill) that is called at the very end of the DOM processing.

For the headers and footers, we could play with the [`displayHeaderFooter` option of the Chrome DevTools Protocol](https://chromedevtools.github.io/devtools-protocol/1-3/Page#method-printToPDF).

**Comment by cderv** [comment]
Just to share something I found : https://wkhtmltopdf.org/
Do you already know ? 
It seems interesting to print html to pdf. It is available as binary or with a C API. I'll try it on pagedown, but does not work as it should on my windows environment. We'll see.

**Comment by RLesur** [comment]
I've used wkhtmltopdf this year when I worked on [my first project using CSS paged media](https://github.com/RLesur/weasydoc).

`wkhtmltopdf` is a good pdf rendering tool. However, it has no native support for CSS paged media. It is not surprising because it relies on WebKit. So, I stopped to use it (it was before I discovered paged.js).

Since I worked with paged.js, I've not tried to generate a pdf with wkhtmltopdf. It would be great if you can try even if the pagedmedia project [still recommends chromium or chrome](https://gitlab.pagedmedia.org/tools/pagedjs/wikis/Your-first-document-with-paged.js#6-browsers-supports). I'm sure the paged.js dev team will be interested by your results.
You can find them here: https://mattermost.pagedmedia.org/

**Comment by RLesur** [comment]
I was a little bit obsessed by this problem.
Today, I've an idea, and finally it works very well!
First of all, many thanks to @MilesMcBain: I reuse here your work.

Since my first try with `chradle` to generate a pdf did not work, I made the assumption that we have no native R websocket client (`rstudio/websocket` is in dev, so I forgot it).
There are two main ideas in the script:

1. Even if we have no native R websocket client, we can build one using a browser + a websocket server (thanks to `httpuv`): we can launch a browser in the middle of two websockets servers. If we configure well this browser, it can open two websockets connections and transmit the messages from one server to the other one. Here, the first websockets server is a headless Chrome with the DevTools protocol activated; the second one is a `httpuv`server. The browser in the middle will be any browser (the RStudio viewer, for instance).

1. In order to synchronize the generation of the pdf with the end of `paged.js`, the process is the following:

    - launch a Chrome headless with the DevTools protocol activated (don't navigate now to the `html_paged`document)
    - connect to Chrome headless using websockets
    - add a binding to the Chrome runtime using the [Runtime.addBinding](https://chromedevtools.github.io/devtools-protocol/tot/Runtime#method-addBinding) method.
    - open the `html_paged` document
    - execute this binding at the end of `paged.js`, see [this commit](https://github.com/RLesur/pagedown/commit/3c81ac42133db9808f0360a6b7c4b065c19036d2).
    - when the client receives this message, generate the pdf

Since the code is quite long for an issue discussion, I put it in a gist https://gist.github.com/RLesur/522e0e7e7b75826e2c9d35bdfcaa1a89
There are many room for improvements. But now, we know that we can do it!

**Comment by RLesur** [comment]
I've tested `rstudio/websocket` with the worst available config: windows behind a proxy.
It works well. We could build something on top of `rstudio/websocket`.

**Comment by RLesur** [comment]
As @yihui , I could not sleep a lot since I did the previous tests.
I read some docs about the Chrome DevTools Protocol and I have a new proposal.
It is like the Chrome Remote Interface but now, this 100% in R.
It relies heavily on the websocket and promises packages.

The source code of the proposal is [here](https://gist.github.com/RLesur/637dac37397127aa9db7529d70d0968c).
Below, you can find an R file that shows how could be this interface.
Sorry, I've not made a Rmd, too tired...

```r
library(promises)

# A proposal for a Chrome Remote Interface with R:
source('https://gist.githubusercontent.com/RLesur/637dac37397127aa9db7529d70d0968c/raw/a97155219b787cba91f2b67d538560f4777179c7/crrry.R')

# Detect system configuration ---------------------------------------------
if (!nzchar(bin <- Sys.getenv("HEADLESS_CHROME"))) # same environment variable as hrbrmstr/decapitated
  bin <- "google-chrome"

# Launch Chrome and create a connexion ------------------------------------
cnx <- chrome_init(bin = bin)

# Getting help with the DevTools protocol ---------------------------------
# Chrome ships the description of the DevTools protocol
# So, we can build an interactive help about the DevTools protocol
# It is the same informations as https://chromedevtools.github.io/devtools-protocol/
# List the domains
cnx$protocol %>% list_domains()

# Need a description for the Page domain?
cnx$protocol %>% describe_domain("Page")

# List the commands for the Page domain
cnx$protocol %>% list_commands("Page")

# Need a description of the Page.navigate method?
cnx$protocol %>% describe_method("Page.navigate")

# Playing with Chrome from R ----------------------------------------------
# If you want to see the headless Chrome, go to http://localhost:9222 (open with Chrome and click on the link on the home page)
# We can send a method with send()
send(cnx, Page.enable()) 
# or with a pipe:
cnx %>% send(Page.navigate(url = "https://bookdown.org"))

# The `send` function returns a Promise
# By default, the Promise is fulfilled when Chrome responds to the command
# (the value of the Promise is the parsed data of the Chrome's response)
# We can modify this behavior with the onmessage argument
# The signature of this function is onmessage(id, data, resolve, reject)
# For instance, if we want to resolve the Promise when the message "Page.frameStoppedLoading" is received
pr <- cnx %>% 
  send(Page.navigate(url = "https://ropensci.org"), 
       onmessage = function(id, data, resolve, reject) {
         if (!is.null(data$method))
           if(data$method == "Page.frameStoppedLoading") {
             resolve(data)
             cat("Frame is loaded.\n Look at the promise, it is fulfilled.\n")
           }
       })

pr

# If we use the pipes provided by the promises package
# we can take a screenshot after the Frame is loaded
cnx %>% 
  send(Page.navigate(url = "https://ropensci.org"), 
       onmessage = function(id, data, resolve, reject) {
         if (!is.null(data$method))
           if(data$method == "Page.frameStoppedLoading") {
             resolve(data)
             cat("Frame is loaded.\n")
           }
       }
  ) %...>% 
  { send(cnx, Page.captureScreenshot(fromSurface = FALSE)) } %...>%
  (function(value) {
    writeBin(jsonlite::base64_dec(value$result$data), "screenshot.png")
    cat("Screenshot saved to screenshot.png\n")
  })

# Cool, isn't it?
# We can close Chrome
close_chrome(cnx)

# PDF generation for the pagedown package ---------------------------------
# The whole process is the following
# First, pick an html_paged document:
remotes::install_github('rlesur/pagedown@automation')
rmd_file <- file.path(tempdir(), "index.Rmd")
download.file("https://raw.githubusercontent.com/rstudio/pagedown/master/inst/examples/index.Rmd", rmd_file)
paged_document <- rmarkdown::render(rmd_file)
daemon <- servr::httd(tempdir(), port = 4321)

# Connect R session to Chrome
cnx <- chrome_init(bin = bin)
# Since the connection creation does not (yet) return a Promise, you have to wait for the connexion to Chrome
create_pdf <- cnx %>% 
  {send(cnx, Runtime.enable())} %...>%
  {send(cnx, Page.enable())} %...>%
  {send(cnx, Runtime.addBinding(name = "pagedownListener"))} %...>%
  {send(cnx, Page.navigate(url = "http://localhost:4321"), 
        onmessage = function(id, data, resolve, reject) {
          if (!is.null(data$method))
            if (data$method == "Runtime.bindingCalled") {
              resolve(data)
            }
        }
  )} %...>%
  {send(cnx, Page.printToPDF())} %...>%
  (function(value) {
    writeBin(jsonlite::base64_dec(value$result$data), "book.pdf")
    cat("PDF created and saved to book.pdf.\n")
  })

finally(create_pdf, onFinally = function() {
  close_chrome(cnx)
  servr::daemon_stop(daemon)
})

# TODO : make the connexion function returning a Promise? 
```

**Comment by RLesur** [comment]
Since last week, I worked a lot on this problem. I wrote down all my ideas here: https://github.com/RLesur/crrri
Now, I understand how to implement this feature in pagedown. I'll do a PR.
