### ISSUE TITLE
Test error is CI for revealjs example

### ISSUE THREAD

**Issue by cderv** [rstudio/pagedown#270]
https://github.com/rstudio/pagedown/runs/4841953523?check_suite_focus=true

````
Output created: test-revealjs.html
assertion failed: chrome_print() works with reveal.js presentations
Error from assert("chrome_print() works with reveal.js presentations", { ...  at test-chrome.R#55 
Error: Error: (identical(first_page_text_content, "Test reveal.js")) is not TRUE
Execution halted
````
Possibly related to timeout
````
Error: 1-17 14:21:50] [error] handle_read_frame error: asio.system:10054 (An existing connection was forcibly closed by the remote host.)
````

or something else. 

It only happens on Windows and Mac

**Comment by yihui** [comment]
Since these tests started to fail on Linux, too, I have tweaked them in 6f27778df1acf592206a5a06d01ced04b2d2e0d1. It's unclear to me why the PDF has an empty page at the end, though (so the total number of pages is 6 instead of the expected 5).

**Comment by cderv** [comment]
Thanks for looking into this !
