### ISSUE TITLE
headless_shell not recognised by pagedown::find_chrome

### ISSUE THREAD

**Issue by michaelpaulhirsch** [rstudio/pagedown#279]
First off, thank you for a great package

The chrome binary 'headless_shell' is not found by find_chrome(), but if i modify the find_chrome() function to include 'headless_shell' as an option, I can get it to work with chrome_print().

Is there any plan to include 'headless_shell'?

**Comment by cderv** [comment]
Hi, 

I am discovering `headless_shell` - what it is exactly ? How did you modify the `find_chrome()` function exactly ? 
Please submit a PR and we'll be happy to review.

Note that `find_chrome()` is only a helper to help auto detect some chromium supported version on the system. However, you can use `pagedown::chrome_print()` already with any version you like by specifying the `browser` argument or setting the `PAGEDOWN_CHROME` environment variable.
