### ISSUE TITLE
TODO when upgrading paged.js

### ISSUE THREAD

**Issue by RLesur** [rstudio/pagedown#29]
**paged.js 0.1.23**
0.1.23 makes the layout asynchronous so it will wait for fonts and images to load automatically now.
- [x] remove #26 , see https://gitlab.pagedmedia.org/tools/pagedjs/commit/27d439fce78bf87fbf0a4e8f569fa84c94eed808

**Comment by yihui** [comment]
Please feel free to run `tools/update.R` and push the necessary changes to the master branch. You don't need to send a PR for this case. Thanks!

**Comment by RLesur** [comment]
Before upgrading, I did several tests: there's now a bug using MathJax and paged.js 0.1.23 (I think it comes from MathJax webfonts loading). I warned the pagedmedia.org team. We have to wait.

**Comment by RLesur** [comment]
I tried the newer MathJax and I've still the warnings.
Moreover, I tried the latest version of paged.js (0.1.25 and 0.1.26) that should solve #1 and I have a weird bug (only the first chapter of the bookdown book is rendered). I have to investigate deeply the problem.

**Comment by RLesur** [comment]
I met the paged.js team today, I've worked with them on the remaining bugs. We have to wait for the next release (maybe next week).

**Comment by RLesur** [comment]
I cannot upgrade paged.js for now: there's still a weird bug in `toc` (page numbers in nested `ul` are wrong), this is a regression. Other features are cool.

**Comment by yihui** [comment]
Cool. Thanks for the update!

BTW, it sounds like we'll have to think about automated testing in the future, instead of having you look at the output every time.
