### ISSUE TITLE
chrome_print: Failed to open http://127.0.0.1:7230/favicon.ico

### ISSUE THREAD

**Issue by veroandreo** [rstudio/pagedown#334]
Hello, 

I'm trying to print my CV from an html file using `chrome_print()`, but I'm getting the following:

```
pagedown::chrome_print(input = "resume_es.html", output = "resume_es.pdf")
Error in force(expr) : 
  Failed to generate output. Reason: Failed to open http://127.0.0.1:5800/favicon.ico (HTTP status code: 404)
``` 
The code I use is [here](https://gitlab.com/veroandreo/cv/-/blob/master/render_cv.r?ref_type=heads#L77). 

I checked the source code of chrome_print, but failed to find anything about favicon. I use pagedown 0.20 in R 4.2. I ended up using Ctrl+P from the Chrome directly and it works, but it's not the optimal solution...

Thanks in advance for any hints!

**Comment by cderv** [comment]
This seems a duplicate of 
- https://github.com/rstudio/pagedown/issues/331
- https://github.com/rstudio/pagedown/issues/329

You should check you chrome version, and also update R packages. did you update **pagedown** ?

**Comment by yihui** [comment]
I think so. [The solution](https://github.com/rstudio/pagedown/issues/329#issuecomment-2319181678) is `install.packages('servr')`.

**Comment by veroandreo** [comment]
That worked, thanks!
