### ISSUE TITLE
Wrong page references in table of contents

### ISSUE THREAD

**Issue by RLesur** [rstudio/pagedown#35]
Since Paged.js 0.1.28 (https://github.com/rstudio/pagedown/commit/3168deb12de81d74161754c543ba8720b7abe826), the page numbering in TOC is wrong when we use a TOC depth greater than 1. This happens only with Chrome, not Firefox.  
I declared the issue in the Paged.js project: https://gitlab.pagedmedia.org/tools/pagedjs/issues/89

**Comment by RLesur** [comment]
It is fixed in Paged.js 0.1.29 https://gitlab.pagedmedia.org/tools/pagedjs/issues/89#note_502
However, I get a regression with 0.1.29 (see the page number of the lists of figures and tables):
![paged js-0 1 29](https://user-images.githubusercontent.com/19177171/50371957-1e815780-05c5-11e9-88e4-797ee023a8eb.png)

**Comment by yihui** [comment]
Actually the LOT and LOF are usually not included in the TOC. If you are able to remove these two items from the TOC, that will be great.

**Comment by RLesur** [comment]
I can try to remove LOT and LOF from the TOC. 
However, this will lead to a difference with the LaTeX CRC template where LOT and LOF are referenced in the TOC: https://bookdown.org/yihui/bookdown/bookdown.pdf.
The bug will remain for any section of class `front-matter`.

**Comment by yihui** [comment]
Oh I misremembered. Sorry. Then let's keep them.

**Comment by RLesur** [comment]
> However, I get a regression with 0.1.29 (see the page number of the lists of figures and tables):

I finally found the problem: this is a Chrome redraw issue. This seems to be a well-known bug. 
There are many available hacks to solve this problem (try to Google _Chrome redraw issue_). Only [this one](https://stackoverflow.com/a/24753578/6500804) works for me with Chromium/Ubuntu.

I will upgrade Paged.js to 0.1.31 soon. There is one breaking change (Paged.js CSS variables are now prefixed) but there are many improvements. IMO the most important ones are the fix for page references and the support for the [`marks` property](https://www.w3.org/TR/css-page-3/#marks).

**Comment by yihui** [comment]
Excellent. Thanks!
