### ISSUE TITLE
Take a look at posterdown

### ISSUE THREAD

**Issue by yihui** [rstudio/pagedown#49]
https://twitter.com/brentthorne18/status/1082324297769725953

**Comment by RLesur** [comment]
Interesting thread. Custom column number should be feasible (and also custom row number with CSS Grid).

**Comment by RLesur** [comment]
I think we can close this issue after https://github.com/rstudio/pagedown/commit/e9f7a1d51586a24dcb8a81b958e805ef6f9b128a
