### ISSUE TITLE
Known page break issues

### ISSUE THREAD

**Issue by yihui** [rstudio/pagedown#5]
These have been fixed in #8. We can remove our fix once paged.js has fixed them.

- [x] `li` inside `ul` cannot be broken across pages (otherwise the leftover text on the second page will have the bullet, too).

- [x] `li` inside `ol` will be numbered from 1: https://gitlab.pagedmedia.org/tools/pagedjs/issues/26

**Comment by RLesur** [comment]
fixed in paged.js, see https://gitlab.pagedmedia.org/tools/pagedjs/merge_requests/26

**Comment by yihui** [comment]
Great! Once they release the package to npm, we can update paged.js in our package and remove your previous fix: https://github.com/rstudio/pagedown/blob/master/tools/update.R
