### ISSUE TITLE
hex sticker

### ISSUE THREAD

**Issue by Maschette** [rstudio/pagedown#52]
Have you got a hex sticker yet? 
Can I have a try at designing one?

**Comment by yihui** [comment]
Absolutely! We don't have one, and will definitely appreciate your help!!

**Comment by Maschette** [comment]
great! do you have a color in mind you would like?

**Comment by yihui** [comment]
I don't really have a preference. Black and white as the main color theme would be great for me (like the bookdown sticker: https://github.com/rstudio/bookdown#bookdown).

**Comment by RLesur** [comment]
@Maschette The hex sticker is beautiful! Many thanks!

**Comment by yihui** [comment]
Yes! It is a brilliant and beautiful design!

![pagedown gradient printer](https://user-images.githubusercontent.com/163582/51946195-72623600-23e6-11e9-9e68-e3a5881834a5.png)

**Comment by apreshill** [comment]
Hello! I'd love to add this hex sticker to our https://github.com/rstudio/hex-stickers repository. But to do that, I need a higher resolution version, preferably an `.svg` file (with fonts converted to outlines). The sizes should be 2" high (point to point); 1.73" wide (side to side).

Can someone share this file? Thank you!

**Comment by yihui** [comment]
@apreshill I didn't check the size, but here is the svg version that @Maschette sent to me: [pagedown gradient printer.svg.zip](https://github.com/rstudio/pagedown/files/4984028/pagedown.gradient.printer.svg.zip)

**Comment by apreshill** [comment]
Thank you @yihui  and @Maschette! I put in a pull request with the hexes.

**Comment by Maschette** [comment]
Thanks @apreshill! Keen to see this join the team of other hex stickers. It was originally based of the Rmarkdown SVG so hopefully the size should be right.
