### ISSUE TITLE
Multiple business cards in pagedown

### ISSUE THREAD

**Issue by mariakharitonova** [rstudio/pagedown#55]
Hello, I am trying to create a number of cards on the same page, so that they can be used as name badges. I know I can create a single business card in pagedown but I am not sure how to create multiple in a single file. Can you advise? Thank you!

**Comment by RLesur** [comment]
Do you try to repeat the same content on each card or do you need different contents on cards?

**Comment by mariakharitonova** [comment]
Same format, but different content on each one (e.g. different names).

**Comment by RLesur** [comment]
Thanks, that's clear. We need to modify the business card template for this.

**Comment by RLesur** [comment]
The answer is positive: I think it is feasible. I just wonder what would be the best implementation

- using `div`s with a custom class: the problem I see is for reusing the same content across cards (e.g. same address)
- using an HTML `template` & custom element populated by pandoc variables: it would be easier for reusing default content across cards

In both options, styling with CSS shouldn't be too difficult.
