### ISSUE TITLE
broken link in README

### ISSUE THREAD

**Issue by RLesur** [rstudio/pagedown#57]
I thought I've understood the `tools/website.R` script but it appears that the link behind the JSS screenshot in the README does not work (https://pagedown.rbind.io/jss-paged/).  
I surely did something wrong but I don't understand what.

**Comment by yihui** [comment]
Don't worry. I'll take care of later.

**Comment by yihui** [comment]
You did everything correctly. It was just that Netlify failed to deploy the site for some reason. I just manually triggered the deploy and the link is live now.
