### ISSUE TITLE
where I am supposed to define these css classes?

### ISSUE THREAD

**Issue by Xinzhu-Fang** [rstudio/pagedown#63]
where I am supposed to define these css classes?

_Originally posted by @Xinzhu-Fang in https://github.com/rstudio/pagedown/issues/50#issuecomment-460910293_

**Comment by jdbarillas** [comment]
Based on the [documentation](https://pagedown.rbind.io/#the-css-overriding-mechanism), it seems like you'd create a separate CSS file and include it in the output format:

```
output:
  pagedown::html_paged: 
    css: ["custom_css_file.css", "default-fonts", "default-page", "default"]
```

**Comment by Xinzhu-Fang** [comment]
Thank you.  Should read more caredully as always. 
In my particular this case,  I did this : 
```
output:
  pagedown::html_resume:
    css: ["my_custom.css", "resume"]
```
then it worked.
