### ISSUE TITLE
cannot excute 

### ISSUE THREAD

**Issue by Yufei-Z** [rstudio/pagedown#70]
processing file: test.Rmd
  |................                                                 |  25%
   inline R code fragments

  |................................                                 |  50%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |.................................................                |  75%
  ordinary text without R code

  |.................................................................| 100%
label: unnamed-chunk-1 (with options) 
List of 2
 $ results: chr "asis"
 $ echo   : logi FALSE

output file: test.knit.md

"D:/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS test.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output test.html --smart --email-obfuscation none --lua-filter "C:/Users/zhang/Documents/R/win-library/3.4/pagedown/resources/lua/uri-to-fn.lua" --lua-filter "C:/Users/zhang/Documents/R/win-library/3.4/pagedown/resources/lua/loft.lua" --lua-filter "C:/Users/zhang/Documents/R/win-library/3.4/pagedown/resources/lua/footnotes.lua" --standalone --section-divs --table-of-contents --toc-depth 3 --template "C:\Users\zhang\Documents\R\win-library\3.4\pagedown\resources\html\paged.html" --highlight-style pygments --number-sections --include-in-header "C:\Users\zhang\AppData\Local\Temp\RtmpSa6zVS\rmarkdown-str2a3c6a7c545d.html" --mathjax 
pandoc.exe: unrecognized option `--lua-filter'
unrecognized option `--lua-filter'
unrecognized option `--lua-filter'
Try pandoc.exe --help for more information.
Error: pandoc document conversion failed with error 2
In addition: Warning message:
running command '"D:/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS test.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash --output test.html --smart --email-obfuscation none --lua-filter "C:/Users/zhang/Documents/R/win-library/3.4/pagedown/resources/lua/uri-to-fn.lua" --lua-filter "C:/Users/zhang/Documents/R/win-library/3.4/pagedown/resources/lua/loft.lua" --lua-filter "C:/Users/zhang/Documents/R/win-library/3.4/pagedown/resources/lua/footnotes.lua" --standalone --section-divs --table-of-contents --toc-depth 3 --template "C:\Users\zhang\Documents\R\win-library\3.4\pagedown\resources\html\paged.html" --highlight-style pygments --number-sections --include-in-header "C:\Users\zhang\AppData\Local\Temp\RtmpSa6zVS\rmarkdown-str2a3c6a7c545d.html" --mathjax' had status 2 
Execution halted

**Comment by yihui** [comment]
Please do read README: https://github.com/rstudio/pagedown#pagedown pagedown requires a higher version of Pandoc.
