### ISSUE TITLE
::: aside ::: don't work

### ISSUE THREAD

**Issue by dktanwar** [rstudio/pagedown#72]
Example for reproducibility:

```{r}
---
title: "Someone's resume"
author: Your Name
output: pagedown::html_resume
---


Aside
====================================

Picture, etc.

Contact info
------------------------------------

Email, phone number, ...

Skills
------------------------------------

- One
- Two
- Three

Disclaimer
------------------------------------

A footer in the sidebar.



Main
====================================

Your Name {#title}
------------------------------------

Arbitrary content.

Education {data-icon=graduation-cap}
------------------------------------

### University One

Title

Location

Year

Arbitrary content


Section
---------------

### Subsection

Title

Location

Year

More info

::: aside
Some notes in the sidebar.
:::
```

**Comment by RLesur** [comment]
I am not sure to understand well this issue.
IMO, the `aside` pandoc div _works_ as it is expected to work (even if the result of this example is ugly).

Here's a screenshot I've obtained from the example (I've added some colors on elements to highlight them)
![image](https://user-images.githubusercontent.com/19177171/53132350-c38dc180-356f-11e9-8d61-7561f2bdb2da.png)
With this screenshot, you can see that the `aside` div is present: it overlaps the aside bar content, but it appears.

Do you get a similar result?

**Comment by dktanwar** [comment]
No.

I got:

![screen shot 2019-02-21 at 09 13 58](https://user-images.githubusercontent.com/8986859/53153654-1b044f80-35b9-11e9-8083-201e4903215e.png)

**Comment by dktanwar** [comment]
Here is the `Rmd` `and `html` files:

[test.zip](https://github.com/rstudio/pagedown/files/2888263/test.zip)

**Comment by RLesur** [comment]
Thanks for these extra informations: my guess is about your Pandoc version.
As stated in the [README file](https://github.com/rstudio/pagedown#pagedown), you need Pandoc >= 2.2.3 to use pagedown.
Could you execute `xfun::session_info('rmarkdown')` and paste the result in this thread?

**Comment by dktanwar** [comment]
You got it! That was the problem! Thank you so much!

Good to know about the `xfun` package..

**Comment by dktanwar** [comment]
Another issue:

I am only able to use `aside` thing when I am having this structure:

```markdown
### Subsection

Title

Location

Year

More info

::: aside
Some notes in the sidebar.
:::
```

How to put `aside` comment for any sentence?

What I would like is:

```markdown
- This is comment

::: aside
This is a side comment for above 
:::
```

**Comment by RLesur** [comment]
I'm not sure to understand well your need.
Is something like that suits your need?

    - This is comment [This is a side comment for above]{style="float:right;"}

**Comment by dktanwar** [comment]
Sorry for being not clear.

What I am trying to do is, put 

```markdown
- This is comment [This is a side comment for above]{style="float:**aside;**"}
```

The comment should go in the aside "grey" bar.

**Comment by RLesur** [comment]
Thanks for your explanations.

First of all, the CSS float property has a limited list of values (`aside` is illegal), see https://developer.mozilla.org/en-US/docs/Web/CSS/float#Values

From my understanding of your need, I think that something like that could achieve your goal:

    - This is comment [This is a side comment for above]{style="position:absolute;left:calc(var(--main-width) + var(--sidebar-horizontal-padding));"}

This code is ugly but we can simplify it later. Please, could you test that and tell me if the result is ok for you?

**Comment by dktanwar** [comment]
Yes, this is what I was looking for. Thank you!

I will update you here with a link to my CV, in case you would like to use as an example..

**Comment by cderv** [comment]
Hi @dktanwar, 
the link to your CV we put as example in pagedown readme was no more working. And the repos does not seem to exist.
For now I removed it. Please fill free to provide your new url, I did not find it myself.
Thanks a lot !

**Comment by dktanwar** [comment]
Hi @cderv 

Thank you!
Sorry, I completely forgot to update here the link: https://dktanwar.github.io/CV/Deepak_Tanwar.html

Also, repo: https://github.com/dktanwar/dktanwar.github.io
