### ISSUE TITLE
chrome_print missing text in PDF, not with Google Chrome

### ISSUE THREAD

**Issue by bevalle** [rstudio/pagedown#80]
When using the `pagedown::chrome_print()` function with a large html created with `xaringan`, some content is missing in the pdf file created with this function whereas I do not face this problem if I print the pdf with Google Chrome.

![bug1_pagedown](https://user-images.githubusercontent.com/18534823/53960267-1aee6e80-40e6-11e9-9525-f41af62bbff7.png)

I spent time on trying to reproduce the error with a light example.
I found an easy case to produce the same problem, but I do not know if this will solve my initial problem.

Here it is :

    ---
    title: "Reprex"
    author: "BVA"
    date: "2019-03-07"
    output:
      xaringan::moon_reader:
        lib_dir: libs
        nature:
          highlightStyle: github
          highlightLines: true
          countIncrementalSlides: false
        seal: true
    ---

    ```{css, echo = FALSE}
    @import url(https://fonts.googleapis.com/css?family=Baloo+Bhai);
    .header {
      position: absolute;
      left: 0;
      top: 0;
      height: 4.3%;
      width: 60%;
      margin: 0;
      padding: 0;
      background-color: rgba(255, 192, 0, 1);
      border-bottom-right-radius: 20px;
      font-family: 'Baloo Bhai', sans-serif;
    } 
    ```

    ```{r setup, include=FALSE}
    options(htmltools.dir.version = FALSE)
    ```

    ```{r header-functions, include = FALSE}
    # header
    header <- function(text) {
      
      code <- paste('<div class="header">', 
                    text,
                    '</div> </div>')
      return(code)
    }
    ```

    `r header("Section 1")`

    # Title 1

With `seal: false` : the "Section 1" text if in top left corner is present after `pagedown::chromeprint()`, meanwhile it is not when `seal: true` (see page 2).

![seal_true_false](https://user-images.githubusercontent.com/18534823/53959836-0493e300-40e5-11e9-9b8b-50c5864b9140.png)
 
**Removing the font line in the css** `font-family: 'Baloo Bhai', sans-serif;` is also a way to display the text in the top left corner.

**EDIT**
``` r
xfun::session_info(c('xaringan', 'pagedown'))
#> R version 3.5.2 (2018-12-20)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17134)
#> 
#> Locale:
#>   LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
#>   LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
#>   LC_TIME=French_France.1252    
#> 
#> Package version:
#>   base64enc_0.1.3 BH_1.69.0.1     bookdown_0.9    digest_0.6.18  
#>   evaluate_0.13   glue_1.3.0      graphics_3.5.2  grDevices_3.5.2
#>   highr_0.7       htmltools_0.3.6 httpuv_1.4.5.1  jsonlite_1.6   
#>   knitr_1.21      later_0.8.0     magrittr_1.5    markdown_0.9   
#>   methods_3.5.2   mime_0.6        pagedown_0.2.1  processx_3.2.1 
#>   promises_1.0.1  ps_1.3.0        R6_2.4.0        Rcpp_1.0.0     
#>   rlang_0.3.1     rmarkdown_1.11  servr_0.13.1    stats_3.5.2    
#>   stringi_1.3.1   stringr_1.4.0   tinytex_0.10    tools_3.5.2    
#>   utils_3.5.2     xaringan_0.9.2  xfun_0.5        yaml_2.2.0
```

<sup>Created on 2019-03-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by yihui** [comment]
First, please make sure you are using the latest versions of **xaringan** (>= 0.9) and **pagedown** (>= 0.2). If you update these packages, try `pagedown::chrome_print('your-slides.Rmd')`. If the text is still missing, try a larger `wait` value, e.g. ``pagedown::chrome_print('your-slides.Rmd', wait = 5)``.

**Comment by RLesur** [comment]
@bevalle I am not able to reproduce the issue on win7

``` r
xfun::session_info(c("xaringan", "pagedown"))
#> R version 3.5.1 (2018-07-02)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 7 x64 (build 7601) Service Pack 1
#> 
#> Locale:
#>   LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
#>   LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
#>   LC_TIME=French_France.1252    
#> 
#> Package version:
#>   base64enc_0.1.3 BH_1.69.0.1     bookdown_0.9    digest_0.6.18  
#>   evaluate_0.13   glue_1.3.0.9000 graphics_3.5.1  grDevices_3.5.1
#>   highr_0.7       htmltools_0.3.6 httpuv_1.4.5.1  jsonlite_1.6   
#>   knitr_1.21      later_0.8.0     magrittr_1.5    markdown_0.9   
#>   methods_3.5.1   mime_0.6        pagedown_0.2.1  processx_3.2.1 
#>   promises_1.0.1  ps_1.3.0        R6_2.4.0        Rcpp_1.0.0     
#>   rlang_0.3.1     rmarkdown_1.11  servr_0.13      stats_3.5.1    
#>   stringi_1.3.1   stringr_1.4.0   tinytex_0.10    tools_3.5.1    
#>   utils_3.5.1     xaringan_0.9.2  xfun_0.5.1      yaml_2.2.0
```

<sup>Created on 2019-03-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Can you had extra infos about:

- Chromium/Chrome version (mine: Version 72.0.3626.121)
- attach as a file the log of `chrome_print(..., verbose = 2)`

**Comment by bevalle** [comment]
Thanks for the replies.
Updating to the very last version of `xaringan` and a Rstudio restart gave a perfect result 🎉

**Comment by yihui** [comment]
One more time: https://yihui.name/en/2017/05/when-in-doubt-upgrade/ 😂

**Comment by bevalle** [comment]
I updated today to the last version of `xaringan` and still faced the problem.  
I just needed to restart Rstudio to profit the strength of `pagedown` and simultaneously feeling ashamed of my error.

**Comment by yihui** [comment]
No need to feel ashamed. It is _extremely_ common to forget to update packages or restart the R session! You are certainly not alone :)

**Comment by yihui** [comment]
Look: #82 (another case, within 12 hours). 😁
