### ISSUE TITLE
chrome_print() only prints the first page of  a resume

### ISSUE THREAD

**Issue by Xinzhu-Fang** [rstudio/pagedown#82]
`pagedown::chrome_print('https://rstudio.github.io/pagedown/html-resume.html')` only prints the first page of the example resume. 

The reason I try to use `chrome_print()` instead of simply printing from chrome is that I cannot submit the pdf printed from chrome on some job application portal. I get this error message for doing that:

> This PDF file contains content that cannot be read. Please upload a PDF that was created from word processing or PDF writer software.

The pdf generated by `chrome_print()` is accepted but it only include the first page.

I am doing real job application. Help appreciated. Thanks

**Comment by yihui** [comment]
`xfun::session_info('pagedown')` please.

**Comment by Xinzhu-Fang** [comment]
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200), RStudio 1.1.442

Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

Package version:
  base64enc_0.1.3  bookdown_0.9     digest_0.6.15    evaluate_0.12    glue_1.2.0      
  graphics_3.4.4   grDevices_3.4.4  highr_0.6        htmltools_0.3.6  jsonlite_1.6    
  knitr_1.21       magrittr_1.5     markdown_0.8     methods_3.4.4    mime_0.6        
  pagedown_0.1.2   Rcpp_0.12.16     rmarkdown_1.11.3 stats_3.4.4      stringi_1.1.7   
  stringr_1.3.1    tinytex_0.10     tools_3.4.4      utils_3.4.4      xfun_0.4        
  yaml_2.2.0

**Comment by Xinzhu-Fang** [comment]
I realized that you released a new version yesterday so I did `remotes::install_github('rstudio/pagedown')
` to update.  Now when I do `pagedown::chrome_print('https://rstudio.github.io/pagedown/html-resume.html')` I get this error:

> Error: 'random_port' is not an exported object from 'namespace:servr'


my current session info:

> R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200), RStudio 1.1.442

> Locale:
  LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
  LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
  LC_TIME=English_United States.1252    

> Package version:
  base64enc_0.1.3  BH_1.66.0.1      bookdown_0.9     digest_0.6.15    evaluate_0.12   
  glue_1.2.0       graphics_3.4.4   grDevices_3.4.4  highr_0.6        htmltools_0.3.6 
  httpuv_1.4.3     jsonlite_1.6     knitr_1.21       later_0.7.3      magrittr_1.5    
  markdown_0.8     methods_3.4.4    mime_0.6         pagedown_0.2.1   processx_3.2.1  
  promises_1.0.1   ps_1.3.0         R6_2.3.0         Rcpp_0.12.16     rlang_0.2.1     
  rmarkdown_1.11.3 servr_0.11       stats_3.4.4      stringi_1.1.7    stringr_1.3.1   
  tinytex_0.10     tools_3.4.4      utils_3.4.4      xfun_0.4         yaml_2.2.0

**Comment by yihui** [comment]
One more time: https://yihui.name/en/2017/05/when-in-doubt-upgrade/

**Comment by Xinzhu-Fang** [comment]
I updated packaged and is now able to print that exampel resume succesfully. I am still having touble with mine:
>   Failed to generate output in 30 seconds (timeout).
Will try play with it a little more and ask for help if needed
Thank you for the lesson

**Comment by yihui** [comment]
We have also observed the timeout issue for a few times on Windows, but it feels random. If you retry, you might succeed. If it keeps failing, please provide a URL or the HTML file, and we can see if we are able to reproduce the issue. Thank you very much!

**Comment by Xinzhu-Fang** [comment]
It keeps failing. https://xinzhu-fang.github.io/resume/index.html

**Comment by yihui** [comment]
Thanks! This is reproducible to me, too (I don't know why yet). Reopening this issue. Cc @RLesur

**Comment by RLesur** [comment]
@yihui I'll have a look tonight

**Comment by RLesur** [comment]
My guess is that the bug comes from the use of `self_contained: true`.

@Xinzhu-Fang Could you try to render the Rmd file with `self_contained: false`?

**Comment by Xinzhu-Fang** [comment]
I tried this
```
---
title: "my resume"

output:
  pagedown::html_resume:
    css: ["my_custom.css", "resume"]
    self_contained: false

---
```
A new folder called index_files was then created. The issue persists. When I tried to knit again, I got errors:

> Error in normalizePath(path.expand(path), winslash, mustWork) : 
  path[1]="index_files/paged-0.2.1": Access is denied
Calls: <Anonymous> ... html_dependencies_as_string -> lapply -> FUN -> normalizePath
In addition: Warning messages:
1: In dir.create(target_dir) :
  'index_files\font-awesome-5.1.0' already exists
2: In dir.create(target_dir) :
  cannot create dir 'index_files\paged-0.2.1', reason 'Permission denied'
3: In dir.create(dirname(to), recursive = TRUE) :
  cannot create dir 'index_files\paged-0.2.1', reason 'Permission denied'
4: In file.create(to[okay]) :
  cannot create file 'index_files/paged-0.2.1/js/config.js', reason 'Permission denied'
5: In dir.create(dirname(to), recursive = TRUE) :
  cannot create dir 'index_files\paged-0.2.1', reason 'Permission denied'
6: In file.create(to[okay]) :
  cannot create file 'index_files/paged-0.2.1/js/paged.js', reason 'Permission denied'
7: In dir.create(dirname(to), recursive = TRUE) :
  cannot create dir 'index_files\paged-0.2.1', reason 'Permission denied'
8: In file.create(to[okay]) :
  cannot create file 'index_files/paged-0.2.1/js/hooks.js', reason 'Permission denied'
9: In dir.create(dirname(to), recursive = TRUE) :
  cannot create dir 'index_files\paged-0.2.1', reason 'Permission denied'
10: In file.create(to[okay]) :
  cannot create file 'index_files/paged-0.2.1/css/resume.css', reason 'Permission denied'
Execution halted

**Comment by RLesur** [comment]
Thanks, I was wrong: `self_contained: false` is not the problem.

There's something really weird in your HTML file. I think this is linked to a problem with your R (packages) installation.

I've extracted the `config.js` file embedded in your HTML page: 
[config.js.txt](https://github.com/rstudio/pagedown/files/2947573/config.js.txt) (I needed to add the `.txt` extension to upload it on GH).
 
This file should be identical to this one: https://github.com/rstudio/pagedown/blob/master/inst/resources/js/config.js

If you compare both files, you see that they are not identical. The `config.js` file embedded in your HTML file corresponds to an older version of pagedown.

More precisely, this version of `config.js` version was used between this commit https://github.com/rstudio/pagedown/commit/2b46119f4a882aaa3b39e63229b0ce67d0a38f3e and this one https://github.com/rstudio/pagedown/commit/a298314c42003362f8d3fe09e30c8435b6c287ad

I think you installed the development version of pagedown last month. Since then, something went wrong with your R configuration. Did you modify something?

**Comment by Xinzhu-Fang** [comment]
That' s right, I started my job application process last month. I don't think I modified my R configuration except using a dark theme but that doesn't mean anything: I have a bad memory and I don't really know what I am doing most of the time. How can my problem be solved?

**Comment by Xinzhu-Fang** [comment]
I have a git repository for my blogdown website and a directory in public called resume containing the rmd, html, and css for my resume (you are disgusted by my messing with public, don't you). I am fine with adding you to this repo as a collaborator if that helps.

**Comment by RLesur** [comment]
Don't worry. Maybe the following actions could work.

1. In your RStudio project, try to pass the name of your **`Rmd`** file (not the HTML file) to the `pagedown::chrome_print()` function. For instance:
    ```r
    pagedown::chrome_print("resume.Rmd")
     ```
    This might work.

1. If that doesn't work, create a new RStudio project. In this new void RStudio project, create a new `resume.Rmd` file. Then, try `pagedown::chrome_print("resume.Rmd")`

**Comment by Xinzhu-Fang** [comment]
Both methods gave me a pdf  of three pages that only has side bar

> Output created: index.html
Warning messages:
1: MathJax doesn't work with self_contained when not using the rmarkdown "default" template. 

In additon, the second method gave me 

> createTcpServer: permission denied

I added  `self_contained: false` back to the second method, the MathJax warning message disappeard, but the pdf doesn't change

**Comment by Xinzhu-Fang** [comment]
I am so sorry. Your methods worked. I have this accessibility setting on windows that works terrible with the printed pdf. It has been working well with other files/programs but I should have suspected. Thank you so much for the help!

**Comment by RLesur** [comment]
@Xinzhu-Fang No problem. We should mention that pdf files generated by Chrome are not accessible.
We haven't yet checked that html files produced with pagedown are accessible. Tell us if there is any other accessibility issue.
