### ISSUE TITLE
Using a non standard character in chrome_print() input returns an unclear error message

### ISSUE THREAD

**Issue by ColinFay** [rstudio/pagedown#85]
Hey, 

First of all, thanks for the amazing chrome_print(). I just LOVE this functionality! 

I'm using `chrome_print()` to print shiny app elements which are bookmarked. 

I noticed this strange error when using `"` in the url inputs (taking the rstudio gallery example below), which is probably to be found with other parameters. 

``` r
pagedown::chrome_print(
  'https://gallery.shinyapps.io/113-bookmarking-url/?_inputs_&n="France"'
)
#> Error in pagedown::chrome_print("https://gallery.shinyapps.io/113-bookmarking-url/?_inputs_&n=\"France\""): Failed to generate output. Reason: Message must be a valid JSON
```

But it's solved if I use `utils::URLencode` on the URL

``` r 
pagedown::chrome_print(
  utils::URLencode('https://gallery.shinyapps.io/113-bookmarking-url/?_inputs_&n="France"')
)
```

<sup>Created on 2019-03-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

IMHO, the `Reason: Message must be a valid JSON` is a little bit esoteric. 

It could be avoided with adding a simple `input <- utils::URLencode(input)` here: https://github.com/rstudio/pagedown/blob/master/R/chrome.R#L52

Will be happy to make a PR if you feel like it.

**Comment by RLesur** [comment]
Glad you love the chrome_print() function!
Thanks for this bug report!
We'd love a PR! However, I think that the call to `utils::URLencode(input)` should be inserted here: https://github.com/rstudio/pagedown/blob/master/R/chrome.R#L73

**Comment by cderv** [comment]
Let’s not that the issue comes also from the fact that we build Json message manually with `sprintf` using `”` as demiliting string character. 

Here ,  If `'` and `”` are inverted in the call it works. 
```r
pagedown::chrome_print(
  “https://gallery.shinyapps.io/113-bookmarking-url/?_inputs_&n='France'”
)
```

So yes encoding the url work, but we may encounter other issue. However I am not sure there is a lot of other cases where input from users can impact the message send to chrome :thinking:

**Comment by yihui** [comment]
I agree with @cderv: we should definitely call `toJSON()` to guarantee the JSON string is valid when there are dynamic values in the string (`sprintf()` is not robust) just like

https://github.com/rstudio/pagedown/blob/fc26c2f77a212a62e334ba0f1c6f4cf36a14aaa3/R/chrome.R#L344

Please feel free to submit a PR to use the helper function `to_json()` to process other messages that contains dynamic R values (and I don't think `URLencode()` will be necessary after that). Thanks!

**Comment by RLesur** [comment]
Good catch @cderv! :100:
