### ISSUE TITLE
Mike Morrison's Poster Template

### ISSUE THREAD

**Issue by RLesur** [rstudio/pagedown#92]
IMO, this is a really convincing design.
https://twitter.com/mikemorrison/status/1110191245035479041?s=19

**Comment by kbodwin** [comment]
I built a clunky version on top of the "relaxed" template here:
https://github.com/kbodwin/templates/tree/master/morrison-poster

**Comment by RLesur** [comment]
@kbodwin This is a nice start :smiley:! @brentthorne also began to work on a similar template in [**posterdown**](https://github.com/brentthorne/posterdown).

**Comment by gadenbuie** [comment]
I love how this poster format resonated with community! I didn’t really “advertise” this but I also made a version for anyone who’s interested: https://github.com/gerkelab/betterposter

**Comment by RLesur** [comment]
Thanks @gadenbuie!

**Comment by kbodwin** [comment]
Oh, rad!  Thanks @RLesur , @gadenbuie , and @brentthorne.  I'll check those versions out!
