### ISSUE TITLE
resume template hyperlink text color?

### ISSUE THREAD

**Issue by SwampThingPaul** [rstudio/pagedown#93]
Is there a way to change the hyperlink text color in the pagedown resume template. Right now the hyperlink looks likes a "visited" page regardless if the page is visited or not. I have dug through the CSS files but couldn't find a specific argument for changing this feature. Is there a way to change this in the css file? Also changing the text color in HTML/rmarkdown language doesn't work.

**Comment by cderv** [comment]
You can change the color link with css like any other html. 
You can do it inside the document itself from the Rmd file using a css chunk at the beggining
Ex. from template to change url color from blue to green:
````
---
title: "Lijia Yu's resume"
author: Lijia Yu
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
---

```{css}
a {
  color: green
}
```
# the rest of the content follows

````

You can also provide a custom css file with your rule that you would put first in the `css` field from the yaml header, following guidelines https://pagedown.rbind.io/#the-css-overriding-mechanism. 
Something like:
---
title: "Lijia Yu's resume"
author: Lijia Yu
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ["my.css", "resume"]
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
---
````
> Also changing the text color in HTML/rmarkdown language doesn't work.

What did you try ? what is not working ?
