### ISSUE TITLE
Adding blank spaces using custom CSS

### ISSUE THREAD

**Issue by Dr-Joe-Roberts** [rstudio/pagedown#95]
Hello, is it possible to add spaces between the headings and content within sections? I want to achieve the spacings shown in the education section of the image, but in the research experience section. I tried to use custom CSS, but couldn't achieve the desired result. Many thanks. 

![Example](https://user-images.githubusercontent.com/46022022/55404016-f6ec4480-554e-11e9-90af-f181d41464ed.png)

**Comment by RLesur** [comment]
I think that this rule should do the trick:

```css
.details ul {
  padding-top: calc(1em + 0.05in); 
}
```

**Comment by Dr-Joe-Roberts** [comment]
Many thanks for your help. The rule provided in your previous post does introduce a space where required, but it pushes the heading for my consise list back to unwanted position (see image). Is there any way around this? 

![Example](https://user-images.githubusercontent.com/46022022/55459385-5ac24c00-55e7-11e9-8145-bf5308108a9f.png)

This is how I have written the section in markdown. 

![Screenshot 2019-04-03 at 08 07 06](https://user-images.githubusercontent.com/46022022/55459475-8e04db00-55e7-11e9-97b9-29ec60be60bb.png)

**Comment by RLesur** [comment]
As @yihui would certainly say, we are trying to "[fold the blinds](https://giphy.com/gifs/frustrated-annoyed-programming-yYSSBtDgbbRzq)" :smile: .

I hope this new rule will be good:

```css
.details > div:not(.concise) > ul {
  padding-top: calc(1em + 0.05in); 
}
```

**Comment by Dr-Joe-Roberts** [comment]
Apologies for the delayed response, I have been at a conference with limited access to my laptop. 

I have tried the new rule provided in your latest post, but it doesn't seem to have made any difference? There is still no space between the 'key responsibilites' and the list.

**Comment by RLesur** [comment]
No worries!
When I tested with your example, there was no space in the concise format.
I've noticed once that depending on the length of the "place" content and the "location" content, an extra space could be added. I wonder whether it could explain what you observed.

Would it be possible for you to share a reproducible example?

**Comment by Dr-Joe-Roberts** [comment]
Thanks for such a quick response, I really appreciate the amount of help you are providing. I hope these screenshots can suffice for a reproducible example, if not please just let me know and I will be able to provide some tomorrow. 

Concise bullet points, no space: 
![Screenshot 2019-04-05 at 21 52 01](https://user-images.githubusercontent.com/46022022/55655992-9fb7cf80-57ed-11e9-8bbe-ffb13683bb8b.png)

Weird formatting without concise:
![Screenshot 2019-04-05 at 21 52 37](https://user-images.githubusercontent.com/46022022/55656036-b65e2680-57ed-11e9-8b1b-b8ac3a3c2c87.png)

**Comment by RLesur** [comment]
It would be much more helpful for me to help you if you could provide the Rmd file (or a link to the html file on a web server).

**Comment by Dr-Joe-Roberts** [comment]
Yes, of course, my apologies. Please find the relevant files here: https://github.com/Dr-Joe-Roberts/curriculum-vitae

**Comment by Dr-Joe-Roberts** [comment]
Okay, so I have solved the issue of the missing spaces. In order to implement them as I wanted, it is necessary to add `data-concise=true` to the section title after `data-icon` like this: `Employment {data-icon=suitcase data-concise=true}`.

I hope this helps anyone else that reads this thread!
